import type { AgentOutput, Approval, BusinessProfile, ConnectionDraft, ConnectionDraftBundle, FounderMatch, FounderProfile } from '../types'
import { appMode } from '../config/appMode'
import { isRecordArray, loadLocal, saveLocal } from './storage'

const KEY='operator.founderMatches';const now='2026-07-06T09:00:00.000Z'
const seed:FounderMatch[]=[
 {id:'maya-pop-up',name:'Maya Chen (fictional)',businessName:'Sunday Spoon',industry:'Food & hospitality',niche:'Pop-up dining concept',stage:'Testing',location:'London market',goals:['Validate demand','Find collaborators'],matchReason:'Both of you are turning an early offer into a small, testable customer experience.',relevanceScore:94,suggestedApproach:'Compare what each of you is learning from first customers.',tags:['food','validation','local'],status:'suggested',createdAt:now},
 {id:'leo-saas',name:'Leo Martin (fictional)',businessName:'BrieflyHQ',industry:'Software',niche:'Solo SaaS productivity tool',stage:'Building',location:'UK & remote',goals:['Product validation','First customers'],matchReason:'A useful peer for discussing narrow MVP scope and founder-led validation.',relevanceScore:91,suggestedApproach:'Ask to swap one lesson from recent customer conversations.',tags:['saas','mvp','solo-founder'],status:'suggested',createdAt:now},
 {id:'amina-wellness',name:'Amina Okafor (fictional)',businessName:'Quiet Circle',industry:'Wellness',niche:'Community wellbeing product',stage:'Validating',location:'Manchester market',goals:['Build community','Test positioning'],matchReason:'You share an interest in trust, community, and learning before scaling.',relevanceScore:88,suggestedApproach:'Start with a low-pressure exchange about community engagement.',tags:['wellness','community','validation'],status:'suggested',createdAt:now},
 {id:'sam-local',name:'Sam Rivera (fictional)',businessName:'BrightFix Home',industry:'Local services',niche:'Home maintenance service',stage:'Active',location:'Birmingham market',goals:['Improve marketing','Get referrals'],matchReason:'A practical match for comparing simple local marketing and referral systems.',relevanceScore:84,suggestedApproach:'Offer to share one marketing experiment and ask what has worked locally.',tags:['local-service','marketing','referrals'],status:'suggested',createdAt:now},
 {id:'nora-commerce',name:'Nora Patel (fictional)',businessName:'Kindred Shelf',industry:'E-commerce',niche:'First sustainable home product',stage:'Testing',location:'UK online market',goals:['Test first product','Improve offer'],matchReason:'Both businesses can benefit from testing a focused offer before adding range or spend.',relevanceScore:82,suggestedApproach:'Compare how each of you explains value without overclaiming.',tags:['ecommerce','offer','testing'],status:'suggested',createdAt:now},
 {id:'jay-student',name:'Jay Williams (fictional)',businessName:'StudySprint',industry:'Education technology',niche:'Student-built no-code study tool',stage:'Idea',location:'Student & online market',goals:['Build with AI tools','Find a first test group'],matchReason:'A good peer for sharing beginner-friendly, low-cost ways to prototype and test.',relevanceScore:79,suggestedApproach:'Invite a short exchange about the smallest useful prototype.',tags:['student-founder','no-code','ai-tools'],status:'suggested',createdAt:now}
]
const clean=(item:FounderMatch):FounderMatch=>({...item,goals:Array.isArray(item.goals)?item.goals:[],tags:Array.isArray(item.tags)?item.tags:[],status:['suggested','saved','dismissed','drafted'].includes(item.status)?item.status:'suggested'})
export const getFounderMatches=()=>{const stored=loadLocal<FounderMatch[]>(KEY,[],isRecordArray<FounderMatch>);const byId=new Map(stored.filter(item=>typeof item.id==='string').map(item=>[item.id,clean(item)]));if(!appMode.allowsDemoData)return [...byId.values()].filter(item=>!seed.some(demo=>demo.id===item.id));return seed.map(item=>byId.get(item.id)||item)}
export const saveFounderMatches=(items:FounderMatch[])=>saveLocal(KEY,items.map(clean))
export const updateFounderMatch=(items:FounderMatch[],id:string,status:FounderMatch['status'])=>items.map(item=>item.id===id?{...item,status}:item)

export function createConnectionDraft(match:FounderMatch,business?:BusinessProfile,founder?:FounderProfile):ConnectionDraftBundle{
 const createdAt=new Date().toISOString();const approvalId=crypto.randomUUID();const founderName=founder?.name||business?.founderName||'Founder';const company=founder?.companyName||business?.businessName||'my business';const tone=founder?.preferredTone||business?.preferredTone||'warm and straightforward';const cta='Would you be open to a short, no-pressure exchange of notes?'
 const message=`Hi ${match.name.replace(' (fictional)','')},\n\nI’m ${founderName}, building ${company}. Your work on ${match.businessName} stood out because ${match.matchReason.toLowerCase()}\n\nI’d enjoy comparing what we are learning. ${cta}\n\nBest,\n${founderName}`;const shortVersion=`Hi ${match.name.replace(' (fictional)','')} — I’m building ${company}. I think we may have useful lessons to swap around ${match.goals[0]?.toLowerCase()||'early-stage building'}. Open to a short chat?`
 const draft:ConnectionDraft={id:crypto.randomUUID(),matchId:match.id,agentId:'community',title:`Connection draft · ${match.name}`,message,shortVersion,tone,callToAction:cta,riskLevel:'medium',approvalId,createdAt}
 const output:AgentOutput={id:crypto.randomUUID(),agentId:'community',title:draft.title,summary:`A ${tone} connection draft for the fictional founder behind ${match.businessName}.`,plainEnglishSummary:`Your Community Agent prepared a thoughtful introduction and a shorter alternative. Nothing was sent.`,keyFindings:[`Recommended approach: ${match.suggestedApproach}`,`Why this match fits: ${match.matchReason}`,`Tone: ${tone}`,`CTA: ${cta}`],recommendedNextSteps:['Review the draft for accuracy and authenticity.','Personalise one sentence before any future outreach.','Keep outreach one-to-one, optional, and respectful.'],copyableText:`RECOMMENDED APPROACH\n${match.suggestedApproach}\n\nDRAFT MESSAGE\n${message}\n\nSHORT VERSION\n${shortVersion}\n\nCTA\n${cta}\n\nTONE NOTES\n${tone}\n\nSAFETY\nPreview only. No email or DM was sent. No contact details were accessed.`,fullOutput:`FOUNDER CONNECTION DRAFT\n\nMATCH\n${match.name} · ${match.businessName}\n${match.industry} · ${match.stage} · ${match.location}\n\nWHY RELEVANT\n${match.matchReason}\n\nRECOMMENDED APPROACH\n${match.suggestedApproach}\n\nDRAFT MESSAGE\n${message}\n\nSHORT VERSION\n${shortVersion}\n\nCALL TO ACTION\n${cta}\n\nTONE\n${tone}\n\nSAFETY\nThis is a local mock preview. No outreach, email, DM, scraping, contact purchase, or external action occurred.`,tags:['community','connection-draft','fictional-profile','local-mock'],createdAt,usefulnessRating:null,approvalNeeded:true,riskNote:'Level 2 preview only. A real message would require explicit approval and a future server-side integration.',futureIntegrationNote:'No email, social, CRM, contact database, or founder network is connected.',source:'workflow',permissionLevel:2,workflowId:'founder-connections',approvalSummary:'A local approval preview was created for possible future one-to-one outreach. Approving it changes local status only.'}
 const approval:Approval={id:approvalId,title:`Preview future outreach · ${match.name}`,agentId:'community',proposedAction:`Review a possible one-to-one introduction to ${match.name} at ${match.businessName}.`,reason:'Sending a real message would affect another person. No contact channel is connected and nothing will be sent in this MVP.',confidence:match.relevanceScore,riskLevel:'medium',status:'pending',createdAt,updatedAt:createdAt,sourceOutputId:output.id,permissionLevel:2,payloadPreview:JSON.stringify({mode:'simulated-outreach-preview',matchId:match.id,recipient:match.name,message,externalExecution:false},null,2)}
 return {draft,output,approval}
}
