import type { AgentOutput, Approval, DailyFocusSummary, EndOfDayReviewInput, ProjectActionItem, ProjectMilestone, ProjectWorkspaceProject } from '../types'

const riskRank:Record<string,number>={restricted:4,high:3,medium:2,low:1}
export function deriveDailyFocus(projects:ProjectWorkspaceProject[],actions:ProjectActionItem[],milestones:ProjectMilestone[],approvals:Approval[],reports:AgentOutput[],preferredProjectId?:string):DailyFocusSummary{
 const project=projects.find(item=>item.id===preferredProjectId)||projects.find(item=>!['Complete','Paused'].includes(item.status))||projects[0]
 const projectActions=actions.filter(item=>!project||item.projectId===project.id);const priorityRank={high:3,medium:2,low:1}
 const incomplete=projectActions.filter(item=>item.status!=='done').sort((a,b)=>(b.status==='blocked'?1:0)-(a.status==='blocked'?1:0)||priorityRank[b.priority]-priorityRank[a.priority]||new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime())
 const stuckItems=incomplete.filter(item=>item.status==='blocked');const pendingApprovals=approvals.filter(item=>(item.status==='pending'||item.status==='edited')&&(!project||!item.projectId||item.projectId===project.id)).sort((a,b)=>(riskRank[b.riskLevel]||0)-(riskRank[a.riskLevel]||0))
 const latestReport=[...reports].filter(item=>!project||!item.projectId||item.projectId===project.id).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()).sort((a,b)=>Number(b.usefulnessRating==='useful')-Number(a.usefulnessRating==='useful'))[0]
 const nextMilestone=milestones.find(item=>item.projectId===project?.id&&item.status==='active')||milestones.find(item=>item.projectId===project?.id&&item.status==='planned')
 const signal=stuckItems.length?'Review blockers':pendingApprovals.length?'Review pending approval':!incomplete.length?'Create next actions':project&&/marketing|launch/i.test(`${project.type} ${project.name}`)?'Create a marketing draft':'Run Daily Business Briefing'
 const agent=stuckItems.length||!incomplete.length?'founder':pendingApprovals.length?'founder':/website|app|pricing/i.test(incomplete[0]?.title||'')?'engineering':/marketing|launch/i.test(`${project?.type} ${project?.name}`)?'marketing':'founder'
 return {projectId:project?.id,projectName:project?.name,topPriorities:incomplete.slice(0,3),stuckItems,nextMilestone,pendingApprovals,latestReport,suggestedAction:signal,suggestedAgentId:agent,focusMessage:project?`You have ${incomplete.length} open ${incomplete.length===1?'action':'actions'} for ${project.name} today.`:'Create your first project so your AI team can plan the day around it.'}
}
export function enrichDailyBriefing(report:AgentOutput,focus:DailyFocusSummary):AgentOutput{
 const findings=[focus.focusMessage,focus.nextMilestone?`Next milestone: ${focus.nextMilestone.title}.`:'No milestone is active yet.',focus.stuckItems.length?`${focus.stuckItems.length} action${focus.stuckItems.length===1?' is':'s are'} stuck.`:'No actions are currently marked stuck.',focus.pendingApprovals.length?`${focus.pendingApprovals.length} approval${focus.pendingApprovals.length===1?' needs':'s need'} review.`:'No approvals are waiting.']
 const steps=focus.topPriorities.length?focus.topPriorities.map(item=>item.title):['Create a project and add the first next action.']
 const summary=focus.projectName?`Today’s focus for ${focus.projectName}: ${steps[0]}`:focus.focusMessage
 return {...report,summary,plainEnglishSummary:summary,keyFindings:findings,recommendedNextSteps:steps,copyableText:`TODAY’S FOCUS\n\n${steps.map((item,index)=>`${index+1}. ${item}`).join('\n')}\n\nSuggested AI help: ${focus.suggestedAction}\n\nEnd-of-day prompt: What moved forward, what stayed blocked, and what should move to tomorrow?`,fullOutput:`${report.fullOutput}\n\nPROJECT-AWARE DAILY FOCUS\n${findings.map(item=>`• ${item}`).join('\n')}\n\nPRIORITY ACTIONS\n${steps.map((item,index)=>`${index+1}. ${item}`).join('\n')}\n\nSUGGESTED AI TEAM ACTION\n${focus.suggestedAction}\n\nEND-OF-DAY REVIEW\nWhat moved forward, what stayed blocked, and what should move to tomorrow?`,tags:[...new Set([...report.tags,'founder-focus',focus.projectName||'no-project'])]}
}
export function createEndOfDayReport(input:EndOfDayReviewInput,projects:ProjectWorkspaceProject[]):AgentOutput{const project=projects.find(item=>item.id===input.projectId);const now=new Date().toISOString();const summary=`Daily review${project?` for ${project.name}`:''}: ${input.doneToday||'Progress noted locally.'}`;const lines=[['What got done',input.doneToday],['Still blocked',input.stillBlocked],['Move to tomorrow',input.moveToTomorrow],['Note for the AI team',input.noteForAi]];return {id:crypto.randomUUID(),agentId:'founder',title:`End-of-day review${project?` · ${project.name}`:''}`,summary,plainEnglishSummary:summary,keyFindings:lines.filter(([,value])=>value).map(([label,value])=>`${label}: ${value}`),recommendedNextSteps:input.moveToTomorrow?[input.moveToTomorrow]:['Choose tomorrow’s first useful action.'],copyableText:lines.map(([label,value])=>`${label}\n${value||'—'}`).join('\n\n'),fullOutput:`END-OF-DAY REVIEW\n\n${lines.map(([label,value])=>`${label.toUpperCase()}\n${value||'—'}`).join('\n\n')}\n\nSaved locally. Nothing was sent or changed.`,tags:['daily-review','founder-focus',...(project?[project.name]:[])],createdAt:now,usefulnessRating:null,approvalNeeded:false,riskNote:'Low risk · local reflection only.',futureIntegrationNote:'No calendar, email, task system, or external service is connected.',source:'project-workspace',permissionLevel:0,estimatedCostMode:'cheap',projectId:project?.id,sourceProjectTitle:project?.name,projectActionType:'end-of-day-review'} }
