import type { Approval, AgentOutput, OperatorNotice, ProjectActionItem, ProjectMilestone, WorkflowRun } from '../types'
import type { FounderBriefing, FounderBriefingItem, FounderSignalCategory, FounderSignalPriority } from './founderIntelligenceService'
import type { FounderDecisionSummary } from './founderDecisionEngine'
import { loadLocal, saveLocal } from './storage'
import { localDateKey, safeTime } from './founderDateService'

export const FOUNDER_BRIEFING_HISTORY_KEY='founderIntelligence.briefingHistory.v1'
export const FOUNDER_BRIEFING_HISTORY_LIMIT=30
const itemLimit=8
export interface FounderBriefingSnapshotItem{signalKey:string;category:string;priority:string;title:string;relatedEntityType?:string;relatedEntityId?:string}
export interface FounderBriefingSnapshot{id:string;generatedAt:string;localDate:string;signalKeys:string[];signalSummaries:FounderBriefingSnapshotItem[];bestNextAction?:FounderBriefingSnapshotItem;counts:{needsAttention:number;waitingForApproval:number;progress:number;recommendations:number};headline?:string;kind?:'briefing'|'end_of_day';decisionSummary?:Pick<FounderDecisionSummary,'reasoning'|'confidence'|'progressSummary'> & {recommendation?:string}}
export interface FounderBriefingChangeSet{newSignals:FounderBriefingSnapshotItem[];resolvedSignals:FounderBriefingSnapshotItem[];continuingSignals:FounderBriefingSnapshotItem[];escalatedSignals:FounderBriefingSnapshotItem[];changedBestNextAction:boolean}
export interface DailyFounderReviewItem extends FounderBriefingSnapshotItem{summary?:string}
export interface DailyFounderReview{localDate:string;headline:string;changed:DailyFounderReviewItem[];completed:DailyFounderReviewItem[];stillOpen:DailyFounderReviewItem[];canWait:DailyFounderReviewItem[];recommendedNextMove?:DailyFounderReviewItem}
export interface EndOfDayFounderReview{generatedAt:string;completedToday:DailyFounderReviewItem[];stillOpen:DailyFounderReviewItem[];snoozed:DailyFounderReviewItem[];waitingForApproval:DailyFounderReviewItem[];suggestedTomorrowStart?:DailyFounderReviewItem}
export interface FounderReviewContext{projectActions:ProjectActionItem[];projectMilestones:ProjectMilestone[];approvals:Approval[];workflowRuns:WorkflowRun[];reports:AgentOutput[];operatorNotices:OperatorNotice[]}

const validItem=(v:unknown):v is FounderBriefingSnapshotItem=>!!v&&typeof v==='object'&&typeof (v as FounderBriefingSnapshotItem).signalKey==='string'&&typeof (v as FounderBriefingSnapshotItem).title==='string'
function sanitizeSnapshot(v:unknown):FounderBriefingSnapshot|null{if(!v||typeof v!=='object')return null;const s=v as Partial<FounderBriefingSnapshot>;if(typeof s.generatedAt!=='string'||typeof s.localDate!=='string')return null;const signalSummaries=Array.isArray(s.signalSummaries)?s.signalSummaries.filter(validItem).slice(0,itemLimit):[];const signalKeys=Array.isArray(s.signalKeys)?s.signalKeys.filter((x):x is string=>typeof x==='string'):signalSummaries.map(i=>i.signalKey);return {id:typeof s.id==='string'?s.id:`briefing-${s.localDate}`,generatedAt:s.generatedAt,localDate:s.localDate,signalKeys,signalSummaries,bestNextAction:s.bestNextAction&&validItem(s.bestNextAction)?s.bestNextAction:undefined,counts:{needsAttention:Number(s.counts?.needsAttention)||0,waitingForApproval:Number(s.counts?.waitingForApproval)||0,progress:Number(s.counts?.progress)||0,recommendations:Number(s.counts?.recommendations)||0},headline:typeof s.headline==='string'?s.headline:undefined,kind:s.kind==='end_of_day'?'end_of_day':'briefing',decisionSummary:s.decisionSummary&&typeof s.decisionSummary==='object'?s.decisionSummary as FounderBriefingSnapshot['decisionSummary']:undefined} }
export function loadFounderBriefingHistory():FounderBriefingSnapshot[]{return loadLocal(FOUNDER_BRIEFING_HISTORY_KEY,[],(v):v is unknown[]=>Array.isArray(v)).map(sanitizeSnapshot).filter((x):x is FounderBriefingSnapshot=>!!x).sort((a,b)=>safeTime(b.generatedAt)-safeTime(a.generatedAt)).filter((s,i,all)=>i===all.findIndex(x=>x.localDate===s.localDate&&x.kind===s.kind)).slice(0,FOUNDER_BRIEFING_HISTORY_LIMIT)}
export function saveFounderBriefingHistory(items:FounderBriefingSnapshot[]):boolean{return saveLocal(FOUNDER_BRIEFING_HISTORY_KEY,items.map(sanitizeSnapshot).filter(Boolean).slice(0,FOUNDER_BRIEFING_HISTORY_LIMIT))}
const toItem=(item:FounderBriefingItem):FounderBriefingSnapshotItem=>({signalKey:item.dismissalKey,category:item.category,priority:item.priority,title:item.title,relatedEntityType:item.relatedEntity.type,relatedEntityId:item.relatedEntity.id})
export function createFounderBriefingSnapshot(briefing:FounderBriefing,date=new Date(),decisionSummary?:FounderBriefingSnapshot['decisionSummary']):FounderBriefingSnapshot{const signalSummaries=briefing.items.map(toItem).slice(0,itemLimit);return {id:`briefing-${localDateKey(date)}`,generatedAt:date.toISOString(),localDate:localDateKey(date),signalKeys:signalSummaries.map(i=>i.signalKey),signalSummaries,bestNextAction:briefing.bestNextAction?toItem(briefing.bestNextAction):undefined,counts:{needsAttention:signalSummaries.filter(i=>i.category==='needs_attention').length,waitingForApproval:signalSummaries.filter(i=>i.category==='waiting_for_approval').length,progress:signalSummaries.filter(i=>i.category==='what_changed').length,recommendations:signalSummaries.filter(i=>i.category==='best_next_action').length},headline:briefing.isEmpty?'No major changes since your last briefing.':briefing.bestNextAction?.title||signalSummaries[0]?.title||'Founder briefing',kind:'briefing',decisionSummary} }
const signature=(s:FounderBriefingSnapshot)=>JSON.stringify({keys:s.signalKeys,items:s.signalSummaries.map(i=>[i.signalKey,i.category,i.priority,i.title,i.relatedEntityType,i.relatedEntityId]),best:s.bestNextAction?[s.bestNextAction.signalKey,s.bestNextAction.title]:null,counts:s.counts,kind:s.kind,decision:s.decisionSummary})
export function upsertMeaningfulBriefingSnapshot(snapshot:FounderBriefingSnapshot):{history:FounderBriefingSnapshot[];changed:boolean;previous?:FounderBriefingSnapshot}{const history=loadFounderBriefingHistory();const today=history.find(s=>s.localDate===snapshot.localDate&&s.kind==='briefing');const previous=history.find(s=>s.localDate!==snapshot.localDate&&s.kind==='briefing');if(today&&signature(today)===signature(snapshot))return {history,changed:false,previous};const next=[snapshot,...history.filter(s=>!(s.localDate===snapshot.localDate&&s.kind==='briefing'))].sort((a,b)=>safeTime(b.generatedAt)-safeTime(a.generatedAt)).slice(0,FOUNDER_BRIEFING_HISTORY_LIMIT);saveFounderBriefingHistory(next);return {history:next,changed:true,previous}}
const priorityRank:Record<string,number>={critical:4,high:3,medium:2,low:1}
export function compareFounderBriefings(current:FounderBriefingSnapshot,previous?:FounderBriefingSnapshot):FounderBriefingChangeSet{if(!previous)return {newSignals:current.signalSummaries,resolvedSignals:[],continuingSignals:[],escalatedSignals:[],changedBestNextAction:false};const prev=new Map(previous.signalSummaries.map(i=>[i.signalKey,i]));const cur=new Map(current.signalSummaries.map(i=>[i.signalKey,i]));const continuing=current.signalSummaries.filter(i=>prev.has(i.signalKey));return {newSignals:current.signalSummaries.filter(i=>!prev.has(i.signalKey)),resolvedSignals:previous.signalSummaries.filter(i=>!cur.has(i.signalKey)),continuingSignals:continuing,escalatedSignals:continuing.filter(i=>(priorityRank[i.priority]||0)>(priorityRank[prev.get(i.signalKey)?.priority||'']||0)),changedBestNextAction:(current.bestNextAction?.signalKey||'')!==(previous.bestNextAction?.signalKey||'')}}
function resolvedToday(ctx:FounderReviewContext,localDate:string):DailyFounderReviewItem[]{const items:DailyFounderReviewItem[]=[];ctx.projectActions.filter(a=>a.status==='done'&&localDateKey(a.completedAt||a.updatedAt)===localDate).forEach(a=>items.push({signalKey:`action:${a.id}`,category:'completed',priority:a.priority,title:a.title,relatedEntityType:'projectAction',relatedEntityId:a.id}));ctx.projectMilestones.filter(m=>m.status==='completed'&&localDateKey(m.completedAt||m.updatedAt)===localDate).forEach(m=>items.push({signalKey:`milestone:${m.id}`,category:'completed',priority:'medium',title:m.title,relatedEntityType:'milestone',relatedEntityId:m.id}));ctx.approvals.filter(a=>!['pending','edited'].includes(a.status)&&localDateKey(a.decidedAt||a.updatedAt||a.approvedAt||a.rejectedAt)===localDate).forEach(a=>items.push({signalKey:`approval:${a.id}`,category:'completed',priority:a.riskLevel,title:a.title,relatedEntityType:'approval',relatedEntityId:a.id}));ctx.workflowRuns.filter(r=>r.status==='completed'&&localDateKey(r.completedAt||r.updatedAt)===localDate).forEach(r=>items.push({signalKey:`workflow:${r.id}`,category:'completed',priority:'low',title:r.workflowName,relatedEntityType:'workflowRun',relatedEntityId:r.id}));ctx.operatorNotices.filter(n=>n.status==='completed'&&localDateKey(n.createdAt)===localDate).forEach(n=>items.push({signalKey:`notice:${n.id}`,category:'completed',priority:n.riskLevel,title:n.title,relatedEntityType:'notice',relatedEntityId:n.id}));return items.slice(0,4)}
export function createDailyFounderReview(current:FounderBriefingSnapshot,previous:FounderBriefingSnapshot|undefined,ctx:FounderReviewContext):DailyFounderReview{const changes=compareFounderBriefings(current,previous);const completed=[...resolvedToday(ctx,current.localDate),...changes.resolvedSignals].slice(0,4);const changed=[...changes.escalatedSignals,...changes.newSignals].slice(0,3);const stillOpen=current.signalSummaries.filter(i=>i.category!=='can_wait'&&i.category!=='best_next_action').slice(0,3);const canWait=current.signalSummaries.filter(i=>i.category==='can_wait'||i.priority==='low').slice(0,2);const headline=!previous?'This is your first Founder Briefing. Future briefings will show what changed.':changed.length||completed.length?`${completed.length?`${completed.length} completed`:''}${completed.length&&changed.length?' and ':''}${changed.length?`${changed.length} new or escalated`:''} since your last briefing.`:'No major changes since your last briefing.';return {localDate:current.localDate,headline,changed,completed,stillOpen,canWait,recommendedNextMove:current.bestNextAction}}
export function createEndOfDayFounderReview(snapshot:FounderBriefingSnapshot,ctx:FounderReviewContext):EndOfDayFounderReview{return {generatedAt:new Date().toISOString(),completedToday:resolvedToday(ctx,snapshot.localDate),stillOpen:snapshot.signalSummaries.filter(i=>i.category==='needs_attention').slice(0,4),snoozed:[],waitingForApproval:snapshot.signalSummaries.filter(i=>i.category==='waiting_for_approval').slice(0,4),suggestedTomorrowStart:snapshot.bestNextAction}}
export function saveEndOfDaySnapshot(review:EndOfDayFounderReview,base:FounderBriefingSnapshot):boolean{const snapshot:{ } & FounderBriefingSnapshot={...base,id:`end-of-day-${base.localDate}`,generatedAt:review.generatedAt,kind:'end_of_day',headline:review.suggestedTomorrowStart?`Tomorrow can start with ${review.suggestedTomorrowStart.title}.`:'End-of-day review saved.'};const history=loadFounderBriefingHistory().filter(s=>!(s.localDate===base.localDate&&s.kind==='end_of_day'));return saveFounderBriefingHistory([snapshot,...history].sort((a,b)=>safeTime(b.generatedAt)-safeTime(a.generatedAt)).slice(0,FOUNDER_BRIEFING_HISTORY_LIMIT))}
