import type { AgentOutput, Approval, CompanyMemoryEvent, FounderProfile, OperatorNotice, ProjectActionItem, ProjectMilestone, ProjectWorkspaceProject, Workflow, WorkflowRun } from '../types'
import { loadLocal, saveLocal } from './storage'
import { isSignalStillRelevant, type FounderResolutionContext } from './founderSignalResolution'
import type { FounderSignalState } from './founderSignalStateService'

export type FounderSignalCategory='needs_attention'|'waiting_for_approval'|'what_changed'|'can_wait'|'best_next_action'
export type FounderSignalPriority='critical'|'high'|'medium'|'low'
export type FounderSignalSource='project'|'approval'|'report'|'workflow'|'notice'|'memory'|'recommendation'
export interface FounderBriefingAction{label:string;target:'workspace'|'approvals'|'reports'|'workflows';workflowId?:string;kind:'navigate'|'run_workflow'|'mark_reviewed'|'snooze';snoozeOption?:'later_today'|'tomorrow'|'next_week'}
export interface FounderBriefingItem{id:string;dismissalKey:string;category:FounderSignalCategory;priority:FounderSignalPriority;source:FounderSignalSource;title:string;happened:string;whyItMatters:string;nextAction:string;area:'Projects'|'Approvals'|'Reports'|'Workflows';requiresApproval:boolean;action:FounderBriefingAction;secondaryAction?:FounderBriefingAction;timestamp:string;relatedEntity:{type:string;id:string};rank:number;allowTemporaryDismiss:boolean}
export interface FounderBriefing{generatedAt:string;items:FounderBriefingItem[];bestNextAction?:FounderBriefingItem;isEmpty:boolean}
export interface FounderBriefingInput{founderProfile:FounderProfile;workflows:Workflow[];reports:AgentOutput[];approvals:Approval[];projects:ProjectWorkspaceProject[];projectActions:ProjectActionItem[];projectMilestones:ProjectMilestone[];operatorNotices:OperatorNotice[];workflowRuns:WorkflowRun[];memoryEvents:CompanyMemoryEvent[];dismissedKeys?:string[];signalStates?:FounderSignalState[]}

const DISMISSED_KEY='founderIntelligence.dismissedSignals'
export const founderBriefingSections:Array<{category:FounderSignalCategory;label:string}>=[
 {category:'needs_attention',label:'Needs attention'}, {category:'waiting_for_approval',label:'Waiting for approval'}, {category:'what_changed',label:'What changed'}, {category:'can_wait',label:'Can wait'}, {category:'best_next_action',label:'Best next action'}
]

export function loadDismissedFounderSignals():string[]{return loadLocal(DISMISSED_KEY,[],(v):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==='string'))}
export function saveDismissedFounderSignals(keys:string[]):boolean{return saveLocal(DISMISSED_KEY,Array.from(new Set(keys)).slice(-80))}

const ts=(value?:string)=>value||new Date(0).toISOString()
const projectName=(projects:ProjectWorkspaceProject[],id?:string)=>projects.find(p=>p.id===id)?.name||'your project'
const priorityWeight:Record<FounderSignalPriority,number>={critical:400,high:300,medium:200,low:100}
const categoryWeight:Record<FounderSignalCategory,number>={needs_attention:80,waiting_for_approval:70,what_changed:45,can_wait:10,best_next_action:0}
const stampScore=(value:string)=>Math.min(50,Math.floor((new Date(value).getTime()||0)/86400000)%50)
const isWorkflowRun=(item:WorkflowRun|AgentOutput):item is WorkflowRun=>'workflowName' in item
const signalTime=(item:WorkflowRun|AgentOutput)=>isWorkflowRun(item)?item.completedAt||item.updatedAt:item.createdAt

export function collectFounderSignals(input:FounderBriefingInput):FounderBriefingItem[]{
 const signals:FounderBriefingItem[]=[]
 input.projectActions.filter(a=>a.status==='blocked'||(a.priority==='high'&&a.status!=='done')).forEach(action=>signals.push({id:`action-${action.id}`,dismissalKey:`action:${action.id}:${action.status}:${action.updatedAt}`,category:'needs_attention',priority:action.status==='blocked'?'critical':'high',source:'project',title:action.status==='blocked'?`Unblock ${action.title}`:`Continue ${action.title}`,happened:`${projectName(input.projects,action.projectId)} has ${action.status==='blocked'?'a blocked action':'a high-priority action'}: ${action.title}.`,whyItMatters:action.status==='blocked'?'Blocked work can stall the next useful step unless you decide how to move it forward.':'This is the strongest unfinished project action in your local board.',nextAction:'Open the project board and decide the next safe step.',area:'Projects',requiresApproval:false,action:{label:'Open project board',target:'workspace',kind:'navigate'},secondaryAction:{label:'Snooze until tomorrow',target:'workspace',kind:'snooze',snoozeOption:'tomorrow'},timestamp:ts(action.updatedAt),relatedEntity:{type:'projectAction',id:action.id},rank:0,allowTemporaryDismiss:action.status!=='blocked'}))
 input.approvals.filter(a=>a.status==='pending'||a.status==='edited').forEach(approval=>signals.push({id:`approval-${approval.id}`,dismissalKey:`approval:${approval.id}:${approval.status}:${approval.updatedAt||approval.createdAt}`,category:'waiting_for_approval',priority:approval.riskLevel==='high'||approval.permissionLevel===2?'high':'medium',source:'approval',title:approval.status==='edited'?`Review edited approval: ${approval.title}`:`Approve or reject: ${approval.title}`,happened:`${approval.title} is waiting for your decision.`,whyItMatters:approval.reason||'Nothing external can happen until you review it, so this is safely paused.',nextAction:'Review the proposed action and approve, edit, or reject it.',area:'Approvals',requiresApproval:true,action:{label:'Review approval',target:'approvals',kind:'navigate'},timestamp:ts(approval.updatedAt||approval.createdAt),relatedEntity:{type:'approval',id:approval.id},rank:0,allowTemporaryDismiss:false}))
 input.reports.filter(r=>(r.riskNote||'').toLowerCase().includes('high')||r.approvalNeeded||r.permissionLevel===2).slice(0,4).forEach(report=>signals.push({id:`report-risk-${report.id}`,dismissalKey:`report:${report.id}:${report.usefulnessRating||'new'}`,category:'needs_attention',priority:report.approvalNeeded?'high':'medium',source:'report',title:`Review ${report.title}`,happened:`A saved report flagged a decision or risk that may need your attention.`,whyItMatters:report.summary||'The report may affect what you do next.',nextAction:'Open the report and review the recommended next steps.',area:'Reports',requiresApproval:!!report.approvalNeeded,action:{label:'Open report',target:'reports',kind:'navigate'},secondaryAction:{label:'Mark reviewed',target:'reports',kind:'mark_reviewed'},timestamp:ts(report.createdAt),relatedEntity:{type:'report',id:report.id},rank:0,allowTemporaryDismiss:true}))
 input.projectMilestones.filter(m=>m.status==='active'||m.status==='planned').slice(0,4).forEach(m=>signals.push({id:`milestone-${m.id}`,dismissalKey:`milestone:${m.id}:${m.status}:${m.updatedAt}`,category:m.status==='active'?'needs_attention':'can_wait',priority:m.status==='active'?'medium':'low',source:'project',title:m.status==='active'?`Move milestone forward: ${m.title}`:`Upcoming milestone: ${m.title}`,happened:`${projectName(input.projects,m.projectId)} has ${m.status==='active'?'an active':'a planned'} milestone.`,whyItMatters:m.description||'Milestones help keep project work tied to an outcome, not just tasks.',nextAction:'Open the workspace and check whether the next action is clear.',area:'Projects',requiresApproval:false,action:{label:'Open workspace',target:'workspace',kind:'navigate'},secondaryAction:{label:'Snooze until tomorrow',target:'workspace',kind:'snooze',snoozeOption:'tomorrow'},timestamp:ts(m.updatedAt),relatedEntity:{type:'milestone',id:m.id},rank:0,allowTemporaryDismiss:true}))
 ;([...input.workflowRuns.filter(r=>r.status==='completed'),...input.reports] as Array<WorkflowRun|AgentOutput>).sort((a,b)=>new Date(signalTime(b)).getTime()-new Date(signalTime(a)).getTime()).slice(0,3).forEach(item=>{const isRun=isWorkflowRun(item);signals.push({id:`changed-${item.id}`,dismissalKey:`changed:${item.id}:${signalTime(item)}`,category:'what_changed',priority:'low',source:isRun?'workflow':'report',title:isRun?`${item.workflowName} finished`:`Saved: ${item.title}`,happened:isRun?`A local workflow finished and saved its results.`:`${item.title} was saved locally.`,whyItMatters:isRun?'Completed local work may have created report notes, approval previews, or follow-up tasks.':(item.summary||'This saved work can guide the next action.'),nextAction:isRun?'Open reports to review the outcome.':'Open the saved report when you are ready.',area:'Reports',requiresApproval:false,action:{label:'Open report',target:'reports',kind:'navigate'},secondaryAction:{label:'Mark reviewed',target:'reports',kind:'mark_reviewed'},timestamp:ts(signalTime(item)),relatedEntity:{type:isRun?'workflowRun':'report',id:item.id},rank:0,allowTemporaryDismiss:true})})
 input.operatorNotices.filter(n=>n.status==='new'||n.status==='drafted').slice(0,3).forEach(n=>signals.push({id:`notice-${n.id}`,dismissalKey:`notice:${n.id}:${n.status}`,category:n.permissionLevel>=2?'waiting_for_approval':'can_wait',priority:n.riskLevel==='high'?'high':'low',source:'notice',title:n.title,happened:n.summary,whyItMatters:'It is prepared locally and will not do anything unless you review it.',nextAction:n.permissionLevel>=2?'Open approvals before taking action.':'Review it when you have a quiet moment.',area:n.permissionLevel>=2?'Approvals':'Workflows',requiresApproval:n.permissionLevel>=2,action:{label:n.permissionLevel>=2?'Open approvals':'Open workflows',target:n.permissionLevel>=2?'approvals':'workflows',kind:'navigate'},secondaryAction:{label:'Dismiss',target:'workflows',kind:'mark_reviewed'},timestamp:ts(n.createdAt),relatedEntity:{type:'notice',id:n.id},rank:0,allowTemporaryDismiss:n.permissionLevel<2}))
 if(!input.projects.length)return signals
 if(!input.projectActions.some(a=>a.status!=='done'))signals.push(recommend('Create the next project action','Your projects do not have an unfinished action yet.','A clear next action keeps the briefing from becoming a passive status summary.','Open workspace','workspace','Projects','project:no-open-action'))
 else if(input.workflows.some(w=>w.id==='daily'))signals.push(recommend('Run the daily business review','Your local data is ready for a calm review workflow.','It can turn current projects, reports, and approvals into a practical plan without external execution.','Run daily review','workflows','Workflows','workflow:daily','daily'))
 return signals
}
function recommend(title:string,happened:string,whyItMatters:string,label:string,target:FounderBriefingAction['target'],area:FounderBriefingItem['area'],key:string,workflowId?:string):FounderBriefingItem{return{id:`recommend-${key}`,dismissalKey:`recommend:${key}`,category:'best_next_action',priority:'medium',source:'recommendation',title,happened,whyItMatters,nextAction:label,area,requiresApproval:false,action:{label,target,workflowId,kind:workflowId?'run_workflow':'navigate'},secondaryAction:workflowId?{label:'Not today',target,kind:'snooze',snoozeOption:'tomorrow'}:undefined,timestamp:new Date().toISOString(),relatedEntity:{type:'recommendation',id:key},rank:0,allowTemporaryDismiss:true}}
export function rankFounderSignals(signals:FounderBriefingItem[]):FounderBriefingItem[]{return signals.map(s=>({...s,rank:priorityWeight[s.priority]+categoryWeight[s.category]+stampScore(s.timestamp)})).sort((a,b)=>b.rank-a.rank)}
export function deduplicateFounderSignals(signals:FounderBriefingItem[]):FounderBriefingItem[]{const seen=new Set<string>();return signals.filter(s=>{const key=`${s.relatedEntity.type}:${s.relatedEntity.id}`;if(seen.has(key))return false;seen.add(key);return true})}
export function selectBestNextAction(signals:FounderBriefingItem[]):FounderBriefingItem|undefined{const visibleIds=new Set(signals.slice(0,4).map(s=>s.id));const actionable=signals.filter(s=>s.category!=='can_wait'&&!visibleIds.has(s.id));const urgent=actionable.find(s=>s.priority==='critical'||s.priority==='high');const approval=actionable.find(s=>s.source==='approval');const blocked=actionable.find(s=>s.relatedEntity.type==='projectAction'&&s.priority==='critical');return urgent||approval||blocked||actionable.find(s=>s.category==='needs_attention')||actionable.find(s=>s.category==='best_next_action')||signals.find(s=>!visibleIds.has(s.id))||signals[0]}
export function generateFounderBriefing(input:FounderBriefingInput):FounderBriefing{const legacyDismissed=(input.dismissedKeys||[]).map(key=>({signalKey:key,status:'dismissed' as const,firstSeenAt:new Date().toISOString(),lastSeenAt:new Date().toISOString(),relatedEntityType:key.split(':')[0]||'legacy',relatedEntityId:key.split(':')[1]||key}));const states=[...(input.signalStates||[]),...legacyDismissed];const ctx:FounderResolutionContext={approvals:input.approvals,reports:input.reports,projectActions:input.projectActions,projectMilestones:input.projectMilestones,operatorNotices:input.operatorNotices,workflowRuns:input.workflowRuns,workflows:input.workflows};const ranked=deduplicateFounderSignals(rankFounderSignals(collectFounderSignals(input))).filter(s=>isSignalStillRelevant(s,states,ctx));const best=selectBestNextAction(ranked);const withoutBest=ranked.filter(s=>s.id!==best?.id).slice(0,4);const bestItem=best?{...best,category:'best_next_action' as const,title:best.category==='best_next_action'?best.title:`Best next: ${best.nextAction}`} : undefined;const items=[...withoutBest,bestItem].filter(Boolean).slice(0,5) as FounderBriefingItem[];return{generatedAt:new Date().toISOString(),items,bestNextAction:bestItem,isEmpty:items.length===0}}
