import type { AgentOutput, Approval, FounderProfile, OperatorNotice, ProjectActionItem, ProjectMilestone, ProjectWorkspaceProject, Workflow, WorkflowRun } from '../types'
import type { FounderBriefing, FounderBriefingItem } from './founderIntelligenceService'
import type { FounderBriefingSnapshot } from './founderBriefingHistoryService'
import type { FounderSignalState } from './founderSignalStateService'

export type FounderDecisionUrgency='critical'|'high'|'medium'|'low'|'none'
export type FounderDecisionConfidence='High'|'Medium'|'Low'
export interface FounderProgressSummary{completed:number;open:number;waitingApproval:number;dismissed:number}
export interface FounderActionBuckets{actNow:FounderBriefingItem[];reviewSoon:FounderBriefingItem[];canWait:FounderBriefingItem[]}
export interface FounderDecisionSummary{
 highestPriority?:FounderBriefingItem
 whyItMatters:string
 bestNextAction?:FounderBriefingItem
 urgency:FounderDecisionUrgency
 reasoning:string
 confidence:FounderDecisionConfidence
 blockedBy:string[]
 canWait:FounderBriefingItem[]
 completedRecently:FounderBriefingItem[]
 progressSummary:FounderProgressSummary
 momentumSummary:string
 insights:string[]
 actionBuckets:FounderActionBuckets
}
export interface FounderDecisionEngineInput{founderProfile:FounderProfile;briefing:FounderBriefing;approvals:Approval[];workflows:Workflow[];reports:AgentOutput[];projects:ProjectWorkspaceProject[];projectActions:ProjectActionItem[];projectMilestones:ProjectMilestone[];operatorNotices:OperatorNotice[];workflowRuns:WorkflowRun[];dismissedKeys?:string[];signalStates?:FounderSignalState[];previousSnapshot?:FounderBriefingSnapshot}

const priorityOrder:Record<string,number>={critical:4,high:3,medium:2,low:1}
const urgency=(item?:FounderBriefingItem):FounderDecisionUrgency=>!item?'none':item.priority==='critical'?'critical':item.priority==='high'?'high':item.priority==='medium'?'medium':'low'
const confidence=(itemCount:number,hasBest:boolean):FounderDecisionConfidence=>hasBest&&itemCount>1?'High':hasBest?'Medium':'Low'
const unique=(items:FounderBriefingItem[])=>{const seen=new Set<string>();return items.filter(item=>{const key=`${item.relatedEntity.type}:${item.relatedEntity.id}`;if(seen.has(key))return false;seen.add(key);return true})}
const completedItem=(title:string,type:string,id:string):FounderBriefingItem=>({id:`completed-${type}-${id}`,dismissalKey:`completed:${type}:${id}`,category:'what_changed',priority:'low',source:type==='approval'?'approval':type==='workflowRun'?'workflow':'project',title,happened:`${title} was completed in local state.`,whyItMatters:'Completed work shows progress and can reduce the number of open decisions competing for attention.',nextAction:'No action needed.',area:type==='approval'?'Approvals':type==='workflowRun'?'Reports':'Projects',requiresApproval:false,action:{label:'Review history',target:type==='approval'?'approvals':type==='workflowRun'?'reports':'workspace',kind:'navigate'},timestamp:new Date(0).toISOString(),relatedEntity:{type,id},rank:0,allowTemporaryDismiss:false})

function buildBuckets(items:FounderBriefingItem[]):FounderActionBuckets{const ordered=unique([...items].sort((a,b)=>b.rank-a.rank));const actNow=ordered.filter(item=>item.priority==='critical'||item.requiresApproval||item.category==='waiting_for_approval').slice(0,3);const used=new Set(actNow.map(item=>item.id));const reviewSoon=ordered.filter(item=>!used.has(item.id)&&item.category!=='can_wait'&&item.priority!=='low').slice(0,4);reviewSoon.forEach(item=>used.add(item.id));const canWait=ordered.filter(item=>!used.has(item.id)).slice(0,4);return {actNow,reviewSoon,canWait}}
function progress(input:FounderDecisionEngineInput):FounderProgressSummary{return {completed:input.projectActions.filter(a=>a.status==='done').length+input.projectMilestones.filter(m=>m.status==='completed').length+input.workflowRuns.filter(r=>r.status==='completed').length+input.approvals.filter(a=>['approved','rejected','blocked'].includes(a.status)).length,open:input.projectActions.filter(a=>a.status!=='done').length+input.projectMilestones.filter(m=>m.status!=='completed').length,waitingApproval:input.approvals.filter(a=>a.status==='pending'||a.status==='edited').length,dismissed:(input.dismissedKeys||[]).length+(input.signalStates||[]).filter(s=>s.status==='dismissed'||s.status==='snoozed').length}}
function momentum(current:FounderBriefing,previous:FounderBriefingSnapshot|undefined,summary:FounderProgressSummary):string{if(!previous)return 'This is your first recorded briefing, so momentum will become clearer after the next one.';const currentOpen=current.items.filter(item=>item.category!=='can_wait'&&item.category!=='best_next_action').length;const previousOpen=previous.signalSummaries.filter(item=>item.category!=='can_wait'&&item.category!=='best_next_action').length;const currentApprovals=current.items.filter(item=>item.category==='waiting_for_approval').length;if(summary.completed>previous.counts.progress)return 'You completed more work than your previous briefing recorded.';if(currentApprovals<previous.counts.waitingForApproval)return 'Approvals are decreasing.';if(currentOpen===previousOpen&&current.items.filter(item=>previous.signalKeys.includes(item.dismissalKey)).length>=3)return 'Three priorities remain unchanged.';if(currentOpen<previousOpen)return 'Open priorities are decreasing.';return 'No meaningful progress since your last briefing.'}
function insights(input:FounderDecisionEngineInput,buckets:FounderActionBuckets,summary:FounderProgressSummary):string[]{const out:string[]=[];const topArea=input.briefing.bestNextAction?.area;if(topArea)out.push(`${topArea} is the current highest-priority area because it contains the best next action.`);if(summary.waitingApproval>=2)out.push('Approvals are beginning to accumulate.');if(input.projectMilestones.filter(m=>m.status==='completed').length>0&&input.projectMilestones.some(m=>m.status==='active'))out.push('Project milestones are progressing steadily.');if(buckets.canWait.length>buckets.actNow.length)out.push('Most visible work can wait, so the briefing is not asking you to react to everything.');if(!out.length)out.push('The current briefing is calm: no single area is creating unusual pressure.');return out.slice(0,3)}

export function createFounderDecisionSummary(input:FounderDecisionEngineInput):FounderDecisionSummary{const items=unique(input.briefing.items);const buckets=buildBuckets(items);const best=input.briefing.bestNextAction||buckets.actNow[0]||buckets.reviewSoon[0]||buckets.canWait[0];const highest=[...items].sort((a,b)=>(priorityOrder[b.priority]-priorityOrder[a.priority])||(b.rank-a.rank))[0];const completedRecently=[...input.projectActions.filter(a=>a.status==='done').slice(0,2).map(a=>completedItem(a.title,'projectAction',a.id)),...input.approvals.filter(a=>['approved','rejected'].includes(a.status)).slice(0,2).map(a=>completedItem(a.title,'approval',a.id)),...input.workflowRuns.filter(r=>r.status==='completed').slice(0,2).map(r=>completedItem(r.workflowName,'workflowRun',r.id))].slice(0,4);const p=progress(input);const blockedBy=[...input.projectActions.filter(a=>a.status==='blocked').map(a=>a.title),...input.approvals.filter(a=>a.status==='pending'||a.status==='edited').map(a=>a.title)].slice(0,4);return {highestPriority:highest,whyItMatters:best?.whyItMatters||'There are no urgent local signals requiring founder attention right now.',bestNextAction:best,urgency:urgency(best),reasoning:best?`${best.nextAction}. ${best.whyItMatters}`:'No action is recommended because the current local state is clear.',confidence:confidence(items.length,!!best),blockedBy,canWait:buckets.canWait,completedRecently,progressSummary:p,momentumSummary:momentum(input.briefing,input.previousSnapshot,p),insights:insights(input,buckets,p),actionBuckets:buckets}}
