import type { AgentOutput, Approval, BuilderRun, BuilderRunBundle, BuilderWorkflow, ProjectWorkspaceProject } from '../types'
import { createMilestone, createProjectAction } from './projectActionBoardService'
import { isRecordArray, loadLocal, saveLocal } from './storage'

const RUNS_KEY='operator.builderRuns'
const commonNotice='Planning only · saved in this browser · no real action taken.'
const prompt=(id:string,label:string,placeholder:string,helper='A short answer is enough. Using the project details is fine.')=>({id,label,placeholder,helper})

export const builderWorkflows:BuilderWorkflow[]=[
 {id:'business-website',name:'Build My Business Website',description:'Turn your business idea into a clear website plan, page structure, copy direction, and launch checklist.',assignedAgentIds:['engineering','marketing'],category:'website',bestFor:'Websites, local businesses, services, and new offers',inputPrompts:[prompt('goal','What should the website help people do?','Book, buy, join a waitlist, or understand the offer'),prompt('audience','Who is it for?','Busy local business owners')],outputSections:['Website goal','Target audience','Suggested pages','Homepage structure','Copy direction','SEO metadata draft','Technical build plan','Launch checklist','Suggested actions','Suggested milestones','Approval-needed future actions'],suggestedActionTemplates:['Confirm the website goal and main call to action','Draft the homepage copy','Review the page list with a customer','Check the mobile launch checklist'],suggestedMilestoneTemplates:['Website plan approved','Homepage draft ready','Ready for a human launch review'],riskLevel:'medium',permissionLevel:1,requiresApprovalPreview:true,mockOnlyNotice:commonNotice},
 {id:'pricing-page',name:'Create Pricing Page',description:'Shape simple packages and explain their value without confusing customers.',assignedAgentIds:['product','marketing','finance'],category:'offer',bestFor:'Services, subscriptions, products, and early pricing tests',inputPrompts:[prompt('offer','What are you pricing?','Your main service or product'),prompt('customer','Who will compare these options?','Your ideal customer')],outputSections:['Pricing strategy summary','Package or tier ideas','Value explanation','FAQ objections','CTA copy','Trust elements','Suggested actions'],suggestedActionTemplates:['Choose the simplest pricing structure','Check package names with two potential customers','Draft the pricing FAQ','Review claims and price assumptions'],suggestedMilestoneTemplates:['Pricing direction chosen','Pricing page ready for review'],riskLevel:'low',permissionLevel:1,requiresApprovalPreview:false,mockOnlyNotice:commonNotice},
 {id:'offer-page',name:'Create Product Offer Page',description:'Turn your offer into a clear page that explains the problem, promise, proof, and next step.',assignedAgentIds:['product','marketing'],category:'offer',bestFor:'Products, services, launches, and validation pages',inputPrompts:[prompt('offer','What are you offering?','Describe it in one sentence'),prompt('pain','What customer problem does it solve?','The frustrating job or outcome')],outputSections:['Offer summary','Customer pain','Promise and value proposition','Page structure','Sections','CTA','Risk reducers','Suggested actions'],suggestedActionTemplates:['Write the one-sentence offer','Gather one proof or trust signal','Draft the call to action','Ask a customer if the page feels clear'],suggestedMilestoneTemplates:['Offer message agreed','Offer page draft complete'],riskLevel:'low',permissionLevel:1,requiresApprovalPreview:false,mockOnlyNotice:commonNotice},
 {id:'launch-plan',name:'Create Launch Plan',description:'Create a calm, practical sequence for preparing, launching, and learning.',assignedAgentIds:['founder','marketing','customer'],category:'launch',bestFor:'New products, websites, services, and business experiments',inputPrompts:[prompt('outcome','What does a good launch achieve?','Ten conversations, first sale, or waitlist sign-ups'),prompt('date','When do you want to be ready?','A rough week or month')],outputSections:['Launch goal','Audience','Pre-launch tasks','Launch week plan','Content ideas','Outreach ideas','Metrics to watch','Suggested milestones'],suggestedActionTemplates:['Choose one measurable launch goal','Prepare the first three launch messages','Make a list of friendly early testers','Create a simple launch-day checklist'],suggestedMilestoneTemplates:['Pre-launch assets ready','Launch week begins','First launch review complete'],riskLevel:'low',permissionLevel:1,requiresApprovalPreview:false,mockOnlyNotice:commonNotice},
 {id:'first-ad-campaign',name:'Create First Ad Campaign',description:'Prepare a campaign brief, example ads, and a careful budget explanation without launching or spending.',assignedAgentIds:['marketing','finance'],category:'ads',bestFor:'Small campaign experiments after the offer and landing page are clear',inputPrompts:[prompt('goal','What result should the campaign aim for?','Leads, bookings, or landing-page visits'),prompt('budget','What daily budget are you considering?','For explanation only — nothing will be spent')],outputSections:['Campaign goal','Budget explanation','Audience hypothesis','Ad copy options','Creative concepts','Landing page checklist','Mock performance plan','Approval-needed future actions','Safety note'],suggestedActionTemplates:['Check the offer and landing page before ads','Choose one audience hypothesis','Review all ad claims','Define a stop rule before any future spend'],suggestedMilestoneTemplates:['Campaign brief reviewed','Creative drafts ready','Human budget review complete'],riskLevel:'high',permissionLevel:1,requiresApprovalPreview:true,mockOnlyNotice:'Planning only · no Meta connection · no ad launched · no money spent · no customers guaranteed.'},
 {id:'app-idea-plan',name:'Build My App Idea Plan',description:'Turn an app idea into a small MVP plan with screens, features, data, risks, and next steps.',assignedAgentIds:['product','engineering'],category:'app',bestFor:'New app ideas and small software products',inputPrompts:[prompt('problem','What problem should the app solve?','The user problem in plain English'),prompt('user','Who has this problem?','The first type of user to help')],outputSections:['App idea summary','User problem','MVP features','Screens','Data model draft','Tech plan','Risks','Suggested actions','Suggested milestones'],suggestedActionTemplates:['Interview one potential user','Choose the three smallest MVP features','Sketch the core user journey','Review the data model for unnecessary scope'],suggestedMilestoneTemplates:['Problem validated','MVP scope agreed','Prototype ready for user feedback'],riskLevel:'medium',permissionLevel:1,requiresApprovalPreview:true,mockOnlyNotice:'Planning only · no repository is created · no code is pushed · nothing is deployed.'},
 {id:'automation-plan',name:'Create Automation Plan',description:'Map a repetitive task into safe steps with human checkpoints and failure handling.',assignedAgentIds:['operations','engineering'],category:'automation',bestFor:'Repeatable admin, customer, content, or operations work',inputPrompts:[prompt('goal','What repetitive job should become easier?','Describe the current manual task'),prompt('approval','Where should a person stay in control?','Before sending, publishing, paying, or changing records')],outputSections:['Automation goal','Trigger','Inputs','Steps','Human approval points','Failure and edge cases','Tools and integrations for future','Suggested actions','Approval-needed future actions'],suggestedActionTemplates:['Write down the current manual steps','Mark every sensitive decision point','Test the plan with mock data','Define the safe failure state'],suggestedMilestoneTemplates:['Manual process mapped','Approval points agreed','Mock automation test reviewed'],riskLevel:'medium',permissionLevel:1,requiresApprovalPreview:true,mockOnlyNotice:'Planning only · no trigger runs · no external tool or database is changed.'}
]

export const loadBuilderRuns=()=>loadLocal<BuilderRun[]>(RUNS_KEY,[],isRecordArray<BuilderRun>).filter(run=>typeof run.id==='string'&&typeof run.projectId==='string'&&typeof run.builderWorkflowId==='string')
export const saveBuilderRuns=(runs:BuilderRun[])=>saveLocal(RUNS_KEY,runs)
const value=(inputs:Record<string,string>,key:string,fallback:string)=>inputs[key]?.trim()||fallback

export function generateBuilderRun(project:ProjectWorkspaceProject,workflowId:string,inputs:Record<string,string>):BuilderRunBundle{
 const workflow=builderWorkflows.find(item=>item.id===workflowId);if(!workflow)throw new Error('Unknown builder workflow')
 const now=new Date().toISOString();const reportId=crypto.randomUUID();const projectContext=project.description||project.ownerGoal||`${project.name} is a ${project.type.toLowerCase()} project.`
 const sections=workflow.outputSections.map((section,index)=>{
  const details=[`Built for ${project.name} at the ${project.stage.toLowerCase()} stage.`,projectContext,`Start small: ${workflow.suggestedActionTemplates[index%workflow.suggestedActionTemplates.length]}.`,index===0?`Primary input: ${value(inputs,workflow.inputPrompts[0]?.id||'',project.ownerGoal||project.name)}.`:'Review this with a real customer or specialist before making a commitment.']
  return `${section}\n${details.join(' ')}`
 })
 const futureActions=workflow.requiresApprovalPreview?workflow.category==='ads'?['Connect an ad account','Publish the campaign','Spend the proposed ad budget']:workflow.category==='website'?['Create a private GitHub repository','Deploy the website','Connect a custom domain']:workflow.category==='automation'?['Connect future integrations','Trigger the automation','Update an external database']:['Create a source-code repository','Push code','Deploy the app']:[]
 const summary=`Your AI team prepared a ${workflow.name.toLowerCase()} for ${project.name}. It is a local planning document only.`
 const output:AgentOutput={id:reportId,agentId:workflow.assignedAgentIds[0],title:`${workflow.name} · ${project.name}`,summary,plainEnglishSummary:summary,keyFindings:[`Best fit: ${workflow.bestFor}.`,`Project context: ${projectContext}`,`Inputs used: ${workflow.inputPrompts.map(item=>`${item.label}: ${value(inputs,item.id,'project default')}`).join(' · ')}`,workflow.mockOnlyNotice],recommendedNextSteps:workflow.suggestedActionTemplates,copyableText:`${workflow.name.toUpperCase()} — ${project.name}\n\n${sections.join('\n\n')}\n\nBOUNDARY\n${workflow.mockOnlyNotice}`,fullOutput:`GUIDED BUILDER PLAN\n${workflow.name} — ${project.name}\n\n${sections.join('\n\n')}\n\nSUGGESTED MILESTONES\n${workflow.suggestedMilestoneTemplates.map((item,index)=>`${index+1}. ${item}`).join('\n')}\n\nFUTURE ACTIONS THAT NEED APPROVAL\n${futureActions.length?futureActions.map(item=>`• ${item}`).join('\n'):'None for this harmless planning output.'}\n\nSAFETY\n${workflow.mockOnlyNotice}\nThe SmallBiz Agent platform, its navigation, system logic, safety rules, and core workflows cannot be modified by this builder.`,tags:['guided-builder',workflow.category,project.name,'planning-only'],createdAt:now,usefulnessRating:null,approvalNeeded:workflow.requiresApprovalPreview,riskNote:workflow.requiresApprovalPreview?'The plan is safe. Listed future external actions require a separate human review and remain simulated in this MVP.':'Low risk local planning output.',futureIntegrationNote:'Future managed website directions may use Next.js, Tailwind, a private Polsia repository, Render, project.polsia.app, downloadable code, and custom domains. Future managed ads may use creative generation and monitoring. None are connected or executed here.',source:'business-builder',permissionLevel:1,projectId:project.id,sourceProjectTitle:project.name,projectActionType:`builder:${workflow.id}`}
 const milestones=workflow.suggestedMilestoneTemplates.map(title=>createMilestone(project.id,title,`Suggested by ${workflow.name}`))
 const actions=workflow.suggestedActionTemplates.map((title,index)=>createProjectAction(project.id,title,`Suggested by ${workflow.name}`,index===0?'high':'medium',{sourceOutputId:reportId,milestoneId:milestones[Math.min(Math.floor(index/2),milestones.length-1)]?.id}))
 const approvals:Approval[]=futureActions.length?[{id:crypto.randomUUID(),title:`Mock approval preview · ${workflow.name}`,agentId:workflow.assignedAgentIds[0],proposedAction:futureActions.join('; '),reason:'These are possible future external actions. Reviewing this item does not execute them.',confidence:82,riskLevel:workflow.riskLevel,status:'pending',createdAt:now,updatedAt:now,sourceOutputId:reportId,permissionLevel:2,projectId:project.id,payloadPreview:JSON.stringify({mode:'simulated-preview-only',projectId:project.id,workflowId:workflow.id,futureActions,externalExecution:false},null,2)}]:[]
 const run:BuilderRun={id:crypto.randomUUID(),projectId:project.id,builderWorkflowId:workflow.id,createdAt:now,inputs,reportId,generatedActionIds:actions.map(item=>item.id),generatedMilestoneIds:milestones.map(item=>item.id),generatedApprovalIds:approvals.map(item=>item.id)}
 return {run,output,actions,milestones,approvals}
}
