import type { AgentOutput, Approval, ProjectHelpActionType, ProjectHelpBundle, ProjectWorkspaceProject } from '../types'

type HelpTemplate={label:string;agentId:string;summary:(project:ProjectWorkspaceProject)=>string;findings:(project:ProjectWorkspaceProject)=>string[];steps:(project:ProjectWorkspaceProject)=>string[];copy:(project:ProjectWorkspaceProject)=>string;sensitive?:string}
const context=(project:ProjectWorkspaceProject)=>project.description||project.ownerGoal||`A ${project.type.toLowerCase()} project at the ${project.stage.toLowerCase()} stage.`
const templates:Record<ProjectHelpActionType,HelpTemplate>={
 'next-steps':{label:'Plan my next steps',agentId:'founder',summary:project=>`${project.name} needs a short, focused plan that moves it from ${project.stage.toLowerCase()} toward ${project.ownerGoal||'its next useful milestone'}.`,findings:project=>[`Current stage: ${project.stage}.`,`Priority: ${project.priority}.`,project.nextActions.some(item=>!item.done)?`${project.nextActions.filter(item=>!item.done).length} existing next steps still need attention.`:'There are no unfinished next steps yet.'],steps:project=>[`Confirm the smallest useful outcome for ${project.name}.`,'Complete one priority task before adding more scope.','Review progress and update the project notes at the end of the week.'],copy:project=>`NEXT-STEP PLAN — ${project.name}\n\n1. Confirm the smallest useful outcome.\n2. Complete one priority task.\n3. Review evidence and update the plan.\n\nCurrent goal: ${project.ownerGoal||'Choose the next milestone.'}`},
 'product-tasks':{label:'Turn this into product tasks',agentId:'product',summary:project=>`${project.name} can be shaped into a small set of testable product tasks before any external issue is created.`,findings:project=>[`Project context: ${context(project)}`,'The strongest first task should test value before expanding scope.','A GitHub issue draft can be reviewed locally.'],steps:()=>['Clarify the user problem and acceptance criteria.','Prepare the smallest testable change.','Review the issue draft before creating anything externally.'],copy:project=>`GITHUB ISSUE DRAFT — ${project.name}\n\nObjective\nTurn ${context(project)} into one testable improvement.\n\nTasks\n- Confirm the user problem\n- Define acceptance criteria\n- Build the smallest useful change\n- Test the happy path and empty state\n\nGuardrails\nDo not deploy, delete production data, or change the SmallBiz Agent platform.`,sensitive:'Creating a real GitHub issue would affect an external tool.'},
 'marketing-draft':{label:'Create a marketing draft',agentId:'marketing',summary:project=>`A grounded founder-led message can explain ${project.name} without hype or unsupported claims.`,findings:project=>[`The clearest angle is the practical value of ${project.name}.`,'Use one specific problem and one simple call to action.','Keep the tone human and easy to understand.'],steps:()=>['Check the wording against your real offer.','Replace assumptions with evidence where possible.','Copy the draft and edit it in your preferred tool.'],copy:project=>`Most small businesses do not need more noise. They need a simpler way to move useful work forward.\n\nThat is what we are exploring with ${project.name}: ${context(project)}\n\nWhat is the biggest friction you would remove first?`},
 'coding-prompt':{label:'Prepare a coding prompt',agentId:'engineering',summary:project=>`${project.name} is ready for a scoped, ready-to-paste coding prompt with tests and clear boundaries.`,findings:project=>[`Objective: support ${project.ownerGoal||project.name}.`,`Context: ${context(project)}`,'The implementation must stay inside the user-owned project and must not modify the SmallBiz Agent platform.'],steps:()=>['Confirm the acceptance criteria.','Paste the prompt into your chosen coding tool.','Review all code and tests before any merge or deployment.'],copy:project=>`CODING PROMPT — ${project.name}\n\nObjective\n${project.ownerGoal||`Move ${project.name} to its next milestone.`}\n\nContext\n${context(project)}\n\nImplementation\n- Follow the project’s existing conventions\n- Keep the change small and reversible\n- Add accessible empty, loading, and error states\n\nTests\n- Core behaviour\n- Persistence where relevant\n- Mobile layout and keyboard use\n\nGuardrails\nDo not modify SmallBiz Agent core files. Do not add secrets, deploy, or perform external actions.`,sensitive:'Creating an external GitHub issue or handing work to a coding agent would affect another system.'},
 research:{label:'Research this project',agentId:'research',summary:project=>`${project.name} would benefit from comparing a few focused options before committing time or money.`,findings:project=>[`Research question: What is the simplest credible path for ${project.name}?`,'Best option: validate the core need with a small manual test.','Alternative: compare two lightweight approaches before building.','Risk: mock findings are not live market evidence.'],steps:()=>['Choose two options to compare.','List the decision criteria that matter most.','Verify important claims with live sources outside this MVP.'],copy:project=>`RESEARCH SUMMARY — ${project.name}\n\nRecommendation\nStart with a small validation test before committing to a larger build.\n\nPros\n- Lower cost\n- Faster feedback\n- Easier to reverse\n\nCons\n- Limited evidence\n- Manual work at first\n\nLive sources are not connected in this MVP.`},
 'finance-review':{label:'Review admin/finance',agentId:'finance',summary:project=>`${project.name} has a local admin review draft with uncertainty clearly separated from decisions that require an accountant.`,findings:project=>[`Project context: ${context(project)}`,'Matched items: illustrative records with clear references.','Unmatched items: anything without a reliable source document.','Confidence: 72% mock confidence; human verification is required.'],steps:()=>['Compare uncertain items with source documents.','Ask an accountant about tax treatment or partial payments.','Do not reconcile, pay, submit, or record a final decision from this draft.'],copy:project=>`EMAIL DRAFT TO ACCOUNTANT — ${project.name}\n\nHello,\n\nI’m reviewing the admin for ${project.name}. Could you please help me check any unmatched items, partial payments, and the correct tax treatment before I record a decision?\n\nThis is a draft only and no transaction has been reconciled or paid.\n\nThank you.`,sensitive:'Sending an accountant email or changing financial records would affect an external system.'}
}
export const projectHelpActions=(Object.entries(templates) as [ProjectHelpActionType,HelpTemplate][]).map(([id,item])=>({id,label:item.label,agentId:item.agentId}))
export function routeProjectHelpRequest(project:ProjectWorkspaceProject,actionType:ProjectHelpActionType):string{return actionType==='product-tasks'&&['Website','App'].includes(project.type)?'engineering':templates[actionType].agentId}
export function generateProjectHelp(project:ProjectWorkspaceProject,actionType:ProjectHelpActionType):ProjectHelpBundle{
 const template=templates[actionType];const agentId=routeProjectHelpRequest(project,actionType);const now=new Date().toISOString();const findings=template.findings(project);const steps=template.steps(project);const reportId=crypto.randomUUID()
 const output:AgentOutput={id:reportId,agentId,title:`${template.label} · ${project.name}`,summary:template.summary(project),plainEnglishSummary:template.summary(project),keyFindings:findings,recommendedNextSteps:steps,copyableText:template.copy(project),fullOutput:`PROJECT\n${project.name}\n\nHELP REQUEST\n${template.label}\n\nSUMMARY\n${template.summary(project)}\n\nWHAT THE AI TEAM FOUND\n${findings.map(item=>`• ${item}`).join('\n')}\n\nNEXT STEPS\n${steps.map((item,index)=>`${index+1}. ${item}`).join('\n')}\n\nREADY TO COPY\n${template.copy(project)}\n\nSAFETY\nThis is a local mock report. Nothing was sent, changed, paid, reconciled, submitted, deployed, or deleted.`,tags:['project-workspace',project.name,actionType,'local-mock'],createdAt:now,usefulnessRating:null,approvalNeeded:Boolean(template.sensitive),approvalSummary:template.sensitive?`${template.sensitive} A local approval item was created instead of taking that action.`:undefined,riskNote:template.sensitive?'Medium/high context · review required before any future external action.':'Low risk · local planning or draft only.',futureIntegrationNote:'No live provider or external system is connected.',source:'project-workspace',permissionLevel:template.sensitive?2:1,estimatedCostMode:'cheap',projectId:project.id,sourceProjectTitle:project.name,projectActionType:actionType}
 if(!template.sensitive)return {output}
 const approval:Approval={id:crypto.randomUUID(),title:`Review: ${template.label} for ${project.name}`,agentId,proposedAction:`Review the ${template.label.toLowerCase()} draft for ${project.name}.`,reason:`${template.sensitive} Nothing external has been contacted.`,confidence:actionType==='finance-review'?72:86,riskLevel:actionType==='finance-review'?'high':'medium',status:'pending',createdAt:now,updatedAt:now,sourceOutputId:reportId,permissionLevel:2,projectId:project.id,payloadPreview:JSON.stringify({mode:'local-preview',projectId:project.id,projectName:project.name,actionType,externalExecution:false},null,2)}
 return {output,approval}
}

