import type { AgentOutput, ProjectActionItem, ProjectActionStatus, ProjectMilestone } from '../types'
import { isRecordArray, loadLocal, saveLocal } from './storage'

const ACTIONS_KEY='operator.projectActions';const MILESTONES_KEY='operator.projectMilestones'
const cleanAction=(item:ProjectActionItem):ProjectActionItem=>({...item,status:['todo','doing','blocked','done'].includes(item.status)?item.status:'todo',priority:['low','medium','high'].includes(item.priority)?item.priority:'medium',description:typeof item.description==='string'?item.description:'',updatedAt:item.updatedAt||item.createdAt||new Date().toISOString()})
const cleanMilestone=(item:ProjectMilestone):ProjectMilestone=>({...item,status:['planned','active','completed'].includes(item.status)?item.status:'planned',description:typeof item.description==='string'?item.description:'',updatedAt:item.updatedAt||item.createdAt||new Date().toISOString()})
export const loadProjectActions=()=>loadLocal<ProjectActionItem[]>(ACTIONS_KEY,[],isRecordArray<ProjectActionItem>).filter(item=>typeof item.id==='string'&&typeof item.projectId==='string'&&typeof item.title==='string').map(cleanAction)
export const saveProjectActions=(items:ProjectActionItem[])=>saveLocal(ACTIONS_KEY,items.map(cleanAction))
export const loadProjectMilestones=()=>loadLocal<ProjectMilestone[]>(MILESTONES_KEY,[],isRecordArray<ProjectMilestone>).filter(item=>typeof item.id==='string'&&typeof item.projectId==='string'&&typeof item.title==='string').map(cleanMilestone)
export const saveProjectMilestones=(items:ProjectMilestone[])=>saveLocal(MILESTONES_KEY,items.map(cleanMilestone))
export const listActionsForProject=(items:ProjectActionItem[],projectId:string)=>items.filter(item=>item.projectId===projectId)
export function createProjectAction(projectId:string,title:string,description='',priority:ProjectActionItem['priority']='medium',links:Partial<Pick<ProjectActionItem,'milestoneId'|'sourceOutputId'|'sourceApprovalId'>>={}):ProjectActionItem{const now=new Date().toISOString();return {id:crypto.randomUUID(),projectId,title:title.trim(),description:description.trim(),status:'todo',priority,createdAt:now,updatedAt:now,...links}}
export const updateProjectAction=(item:ProjectActionItem,updates:Partial<ProjectActionItem>):ProjectActionItem=>{const status=(updates.status||item.status) as ProjectActionStatus;const now=new Date().toISOString();return {...item,...updates,updatedAt:now,completedAt:status==='done'?(item.completedAt||now):undefined}}
export function createMilestone(projectId:string,title:string,description=''):ProjectMilestone{const now=new Date().toISOString();return {id:crypto.randomUUID(),projectId,title:title.trim(),description:description.trim(),status:'planned',createdAt:now,updatedAt:now}}
export const updateMilestone=(item:ProjectMilestone,updates:Partial<ProjectMilestone>):ProjectMilestone=>{const status=updates.status||item.status;const now=new Date().toISOString();return {...item,...updates,updatedAt:now,completedAt:status==='completed'?(item.completedAt||now):undefined}}
export function actionsFromOutput(projectId:string,output:AgentOutput,existing:ProjectActionItem[]):ProjectActionItem[]{const suggestions=output.recommendedNextSteps?.length?output.recommendedNextSteps:[output.plainEnglishSummary||output.summary];return suggestions.filter(title=>!existing.some(item=>item.projectId===projectId&&item.sourceOutputId===output.id&&item.title.toLowerCase()===title.toLowerCase())).map(title=>createProjectAction(projectId,title,`Suggested by ${output.title}`,'medium',{sourceOutputId:output.id}))}
