import type { ToolDefinition } from '../../types'

const safe=(id:string,name:string,category:string,permissionLevel:0|1):ToolDefinition=>({id,name,description:`Deterministic local ${name.toLowerCase()} tool.`,category,permissionLevel,riskLevel:'low',requiresApproval:false,inputSchemaDescription:'Prompt, agent, workflow, and profile context.',outputSchemaDescription:'Structured mock result with summary and warnings.',enabled:true,isMock:true,futureIntegration:'Replace behind server-side adapter only.'})
export const toolRegistry:ToolDefinition[]=[
 safe('summarize_context','Summarize context','analysis',0),safe('identify_priorities','Identify priorities','planning',0),safe('identify_risks','Identify risks','analysis',0),safe('suggest_next_actions','Suggest next actions','planning',0),safe('identify_bottlenecks','Identify bottlenecks','planning',0),safe('analyse_feedback','Analyse feedback','product',0),safe('draft_github_issue','Draft GitHub issue','engineering',1),safe('suggest_roadmap_item','Suggest roadmap item','product',1),safe('generate_marketing_copy','Generate marketing copy','marketing',1),safe('create_short_version','Create short version','marketing',1),safe('suggest_cta','Suggest CTA','marketing',1),safe('prepare_coding_prompt','Prepare coding prompt','engineering',1),safe('suggest_tests','Suggest tests','engineering',1),safe('review_invoice_data','Review invoice data','finance',1),safe('identify_uncertain_items','Identify uncertain items','finance',0),safe('draft_accountant_email','Draft accountant email','finance',1),safe('compare_options','Compare options','research',0),safe('summarize_sources_mock','Summarize mock sources','research',0),safe('recommend_next_step','Recommend next step','research',0),safe('gmail_summarize_inbox','Gmail summarize inbox','email',0),safe('gmail_classify_priority','Gmail classify priority','email',0),safe('gmail_draft_reply','Gmail draft reply','email',1),safe('calendar_summarize_events','Calendar summarize events','calendar',0),safe('calendar_prioritize_meetings','Calendar prioritize meetings','calendar',0),safe('calendar_draft_briefing','Calendar draft briefing','calendar',1),
 {id:'future_send_email',name:'Future send email',description:'Disabled external Gmail action.',category:'email',permissionLevel:2,riskLevel:'medium',requiresApproval:true,inputSchemaDescription:'Approved recipient, subject, body.',outputSchemaDescription:'External delivery receipt.',enabled:false,isMock:false,futureIntegration:'Gmail backend adapter'},
 {id:'future_calendar_event_write',name:'Future calendar event write',description:'Disabled external Google Calendar create/update/invite action.',category:'calendar',permissionLevel:2,riskLevel:'medium',requiresApproval:true,inputSchemaDescription:'Approved event payload, attendees, and update scope.',outputSchemaDescription:'Calendar event audit receipt.',enabled:false,isMock:false,futureIntegration:'Google Calendar backend OAuth adapter'},
 {id:'future_create_github_issue',name:'Future create GitHub issue',description:'Disabled external GitHub action.',category:'engineering',permissionLevel:2,riskLevel:'medium',requiresApproval:true,inputSchemaDescription:'Repository, title, body.',outputSchemaDescription:'Issue URL and audit record.',enabled:false,isMock:false,futureIntegration:'GitHub backend adapter'},
 {id:'future_xero_invoice_review',name:'Future Xero invoice review',description:'Disabled read-only Xero data adapter.',category:'finance',permissionLevel:2,riskLevel:'high',requiresApproval:true,inputSchemaDescription:'Tenant and invoice scope.',outputSchemaDescription:'Reviewed invoice data.',enabled:false,isMock:false,futureIntegration:'Xero backend adapter'},
 {id:'future_supabase_update',name:'Future Supabase update',description:'Disabled database mutation.',category:'database',permissionLevel:2,riskLevel:'high',requiresApproval:true,inputSchemaDescription:'Table, policy-safe payload.',outputSchemaDescription:'Mutation audit record.',enabled:false,isMock:false,futureIntegration:'Supabase server client with RLS'},
 {id:'future_webhook_trigger',name:'Future webhook trigger',description:'Disabled external workflow trigger.',category:'automation',permissionLevel:2,riskLevel:'high',requiresApproval:true,inputSchemaDescription:'Allowlisted endpoint and payload.',outputSchemaDescription:'Trigger audit result.',enabled:false,isMock:false,futureIntegration:'Backend webhook allowlist'}
]
export const workflowToolMap:Record<string,string[]>={daily:['summarize_context','identify_priorities','identify_risks'],weekly:['summarize_context','suggest_next_actions','identify_bottlenecks'],vexis:['analyse_feedback','draft_github_issue','suggest_roadmap_item'],marketing:['generate_marketing_copy','create_short_version','suggest_cta'],github:['prepare_coding_prompt','draft_github_issue','suggest_tests'],invoice:['review_invoice_data','identify_uncertain_items','draft_accountant_email'],research:['compare_options','summarize_sources_mock','recommend_next_step'],'founder-connections':['summarize_context','compare_options','suggest_next_actions'],'business-plan':['summarize_context','identify_priorities','suggest_next_actions'],funding:['summarize_context','compare_options','identify_risks'],automation:['summarize_context','identify_risks','suggest_next_actions'],'self-audit':['summarize_context','identify_bottlenecks','suggest_next_actions'],'gmail-review':['gmail_summarize_inbox','gmail_classify_priority','gmail_draft_reply'],'calendar-review':['calendar_summarize_events','calendar_prioritize_meetings','calendar_draft_briefing']}
export function getTool(id:string){return toolRegistry.find(tool=>tool.id===id)}
export function getWorkflowTools(workflowId:string){return (workflowToolMap[workflowId]||['summarize_context','suggest_next_actions']).map(getTool).filter((tool):tool is ToolDefinition=>Boolean(tool))}
