import { useState } from 'react'
import { agents } from '../data/agents'
import type { MockAgentResult } from '../types'
import { Badge } from '../components/Badge'

const categories:Record<string,string>={'business-builder':'Start',founder:'Run',product:'Launch',engineering:'Build',marketing:'Launch',finance:'Run',research:'Start',customer:'Run',automation:'Automate','self-improvement':'Improve'}
export function AgentsPage({ submitPrompt }:{submitPrompt:(prompt:string,agentId?:string)=>MockAgentResult;promptResult:MockAgentResult|null}) {
 const [selected,setSelected]=useState<string|null>(null);const [prompt,setPrompt]=useState('');const [localResult,setLocalResult]=useState<MockAgentResult|null>(null)
 const agent=agents.find(a=>a.id===selected)
 const ask=(value=prompt)=>{if(!agent||!value.trim())return;setLocalResult(submitPrompt(value,agent.id));setPrompt('')}
 return <div className="page"><header className="topbar"><div><p className="eyebrow">YOUR SMALL AI BUSINESS TEAM</p><h1>{agents.length} specialists. One command center.</h1><p>Start, launch, run, automate, and improve—with visible boundaries.</p></div><Badge tone="live">Local team ready</Badge></header>
  {agent&&<section className="agent-interaction"><button className="close-panel" aria-label="Close agent panel" onClick={()=>{setSelected(null);setLocalResult(null)}}>×</button><div className="interaction-agent"><span>{agent.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><small>ASKING</small><h2>{agent.name}</h2><p>{agent.defaultOutputFormat}</p></div></div><div className="prompt-chips">{agent.examplePrompts.map(x=><button key={x} onClick={()=>setPrompt(x)}>{x}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask()}}><textarea aria-label={`Prompt for ${agent.name}`} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={`Ask ${agent.name}…`}/><button type="submit">Generate local response →</button></form>{localResult&&<div className={`inline-agent-result ${localResult.blockedReason?'blocked-result':''}`}><Badge tone={localResult.blockedReason?'restricted':'live'}>{localResult.blockedReason?'Blocked':'Saved to reports'}</Badge><h3>{localResult.output?.title||'Level 3 request blocked'}</h3><p>{localResult.blockedReason||localResult.output?.summary}</p>{localResult.approvalDraft&&<small>Level 2 local approval preview created. No external action occurred.</small>}</div>}</section>}
  <div className="agent-grid">{agents.map((a,i)=><article className="agent-card" key={a.id}><div className={`agent-avatar av${i%7}`}>{a.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</div><div><span className="eyebrow">{categories[a.id]} · {a.role}</span><h2>{a.name}</h2><p>{a.description}</p></div><div className="agent-section"><b>Capabilities</b><div className="chips">{a.capabilities.map(c=><span key={c}>{c}</span>)}</div></div><div className="agent-section boundaries"><b>Boundaries</b>{a.boundaries.map(b=><p key={b}>— {b}</p>)}</div><div className="agent-section example"><b>Try asking</b>{a.examplePrompts.slice(0,2).map(x=><p key={x}>“{x}”</p>)}</div><div className="agent-footer"><small>Output · {a.defaultOutputFormat}</small><button onClick={()=>{setSelected(a.id);setPrompt(a.examplePrompts[0]);setLocalResult(null);scrollTo({top:0,behavior:'smooth'})}}>Ask this agent →</button></div></article>)}</div></div>
}
