import { useEffect, useState } from 'react'
import type { Approval, RiskLevel } from '../types'
import { agents } from '../data/agents'
import { Badge } from '../components/Badge'
import { EmptyState } from '../components/EmptyState'
import { PermissionGuide } from '../components/PermissionGuide'

const riskExplanation:Record<RiskLevel,string>={
 low:'Safe to review. This is only a suggestion or draft.',
 medium:'Needs your review because it could affect what you send, publish, or save.',
 high:'Important action. Review carefully before approving.',
 restricted:'Blocked in this MVP. This type of action cannot be completed here.'
}
const willNotDo=['Send emails','Create GitHub issues','Update databases','Trigger external workflows','Reconcile bank transactions','Make payments','Submit tax documents','Delete production data','Make legal or financial commitments']
function approvalActionLabel(approval:Approval){const text=`${approval.title} ${approval.proposedAction}`.toLowerCase();if(text.includes('email')||text.includes('send'))return 'Approve simulated send';if(text.includes('schedule')||text.includes('calendar')||text.includes('meeting'))return 'Approve schedule suggestion';if(text.includes('draft'))return 'Approve draft';return 'Approve recommendation'}

export function ApprovalsPage({approvals,update}:{approvals:Approval[];update:(id:string,updates:Partial<Approval>)=>void}){
 const waiting=approvals.filter(item=>item.status==='pending'||item.status==='edited');const [selectedId,setSelectedId]=useState<string|null>(null);const selected=approvals.find(item=>item.id===selectedId)
 useEffect(()=>{try{const raw=sessionStorage.getItem('founderIntelligence.openTarget');if(!raw)return;const target=JSON.parse(raw) as {type?:string;id?:string};if(target.type==='approval'&&approvals.some(item=>item.id===target.id)){setSelectedId(target.id!);sessionStorage.removeItem('founderIntelligence.openTarget')}}catch{}},[approvals])
 const [action,setAction]=useState('');const [reason,setReason]=useState('');const [editing,setEditing]=useState(false);const [rejecting,setRejecting]=useState(false)
 useEffect(()=>{setAction(selected?.editedAction||selected?.proposedAction||'');setReason(selected?.rejectionReason||'');setEditing(false);setRejecting(false)},[selectedId,selected?.editedAction,selected?.proposedAction,selected?.rejectionReason])
 const restricted=Boolean(selected&&(selected.riskLevel==='restricted'||selected.permissionLevel===3||selected.status==='blocked'));const actionable=Boolean(selected&&(selected.status==='pending'||selected.status==='edited')&&!restricted)
 const approve=()=>{if(!selected||!actionable)return;const now=new Date().toISOString();update(selected.id,{status:'approved',approvedAt:now,decidedAt:now})}
 const reject=()=>{if(!selected||!actionable)return;const now=new Date().toISOString();update(selected.id,{status:'rejected',rejectionReason:reason.trim()||undefined,rejectedAt:now,decidedAt:now});setRejecting(false)}
 return <div className="page approvals-page"><header className="topbar friendly-topbar"><div><p className="eyebrow">YOU’RE IN CONTROL</p><h1>Ready for your approval</h1><p>Prepared decisions from SmallBiz Agent. Approve, edit, or reject — you stay in control.</p></div><Badge tone="warning">{waiting.length} waiting</Badge></header>
  <div className="review-reassurance"><b>Nothing happens secretly.</b><span>Approving only changes a status in this browser. No email, issue, payment, database update, or external action occurs.</span></div><details className="advanced-details permission-details"><summary>See the safety levels</summary><PermissionGuide/></details>
  {selected&&<section className="approval-review"><div className="approval-review-head"><div><div className="meta-row"><Badge tone={selected.riskLevel}>{selected.riskLevel} risk</Badge><Badge tone={selected.status==='blocked'?'restricted':selected.status}>{selected.status}</Badge></div><h2>{selected.title}</h2><p>Prepared by {agents.find(agent=>agent.id===selected.agentId)?.name||'local helper'} · Created {new Date(selected.createdAt).toLocaleString()}</p></div><button aria-label="Close approval detail" onClick={()=>setSelectedId(null)}>×</button></div>
   <div className="approval-review-grid"><section><h3>Prepared action</h3><p>{selected.editedAction||selected.proposedAction}</p></section><section><h3>Why this needs approval</h3><p>{selected.reason}</p></section><section><h3>{selected.riskLevel[0].toUpperCase()+selected.riskLevel.slice(1)} risk</h3><p>{riskExplanation[selected.riskLevel]}</p></section><section><h3>Confidence: {selected.confidence}%</h3><p>{selected.confidence>=85?'The local rules found a strong match, but your judgment still comes first.':selected.confidence>=65?'The suggestion looks reasonable, but important details may need checking.':'There is meaningful uncertainty. Review the details carefully.'}</p></section></div>
	   <section className="approval-outcome"><h3>What happens after approval?</h3><p>This records your decision locally and marks the review complete. It does not carry out the proposed action or contact another service.</p><p><b>Can it be undone?</b> The decision can be reviewed in local history, but no external action exists to undo.</p>{selected.projectId&&<p><b>Affected project:</b> This decision is linked to the project that requested it.</p>}{selected.sourceOutputId&&<p><b>Affected report:</b> This decision was created from a saved report.</p>}</section>
   <section className="never-automatic"><h3>What the app will not do automatically</h3><div>{willNotDo.map(item=><span key={item}>× {item}</span>)}</div></section>
   <section className="editable-approval"><div><h3>Your action preview</h3>{actionable&&!editing&&<button onClick={()=>setEditing(true)}>Edit before approving</button>}</div>{editing?<><textarea aria-label="Edit proposed action" value={action} onChange={event=>setAction(event.target.value)}/><p>Edits stay in this browser and do not trigger the action.</p><div className="edit-actions"><button onClick={()=>{setAction(selected.editedAction||selected.proposedAction);setEditing(false)}}>Cancel</button><button className="primary" disabled={!action.trim()} onClick={()=>{update(selected.id,{proposedAction:action,editedAction:action,status:'edited'});setEditing(false)}}>Save local edit</button></div></>:<p className="action-preview">{selected.editedAction||selected.proposedAction}</p>}{selected.editedAction&&<small>Edited version saved locally.</small>}</section>
   {rejecting&&actionable&&<section className="reject-box"><h3>Reject this suggestion?</h3><label>Reason (optional)<textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Add a short note for your future self"/></label><div><button onClick={()=>{setRejecting(false);setReason(selected.rejectionReason||'')}}>Cancel</button><button className="danger" onClick={reject}>Reject locally</button></div></section>}
   <details className="advanced-details"><summary>View proposed action details</summary><div className="payload-preview"><pre>{selected.payloadPreview||JSON.stringify({mode:'local-preview',action:selected.editedAction||selected.proposedAction,externalExecution:false},null,2)}</pre></div></details>
	   {restricted?<section className="restricted-explainer"><Badge tone="restricted">Blocked in MVP</Badge><div><h3>This action cannot be approved here</h3><p>Payments, reconciliation, tax submissions, deletion, commitments, deployment, and irreversible changes are blocked. Ask SmallBiz Agent for a draft, checklist, or summary to take to a qualified professional instead.</p></div></section>:<div className="approval-decision-actions"><button disabled={!actionable||rejecting} onClick={()=>setRejecting(true)}>Reject recommendation</button><button className="primary" disabled={!actionable||editing||rejecting} onClick={approve}>{approvalActionLabel(selected)}</button></div>}
   <section className="approval-history"><h3>Status history</h3><p><b>Created</b><span>{new Date(selected.createdAt).toLocaleString()}</span></p>{selected.updatedAt&&<p><b>Last updated</b><span>{new Date(selected.updatedAt).toLocaleString()}</span></p>}{selected.approvedAt&&<p><b>Approved locally</b><span>{new Date(selected.approvedAt).toLocaleString()}</span></p>}{selected.rejectedAt&&<p><b>Rejected</b><span>{new Date(selected.rejectedAt).toLocaleString()}</span></p>}{selected.decidedAt&&!selected.approvedAt&&!selected.rejectedAt&&<p><b>Decision recorded</b><span>{new Date(selected.decidedAt).toLocaleString()}</span></p>}{selected.rejectionReason&&<p><b>Rejection note</b><span>{selected.rejectionReason}</span></p>}</section>
  </section>}
  <div className="approval-list friendly-approvals">{approvals.length?approvals.map(item=>{const blocked=item.riskLevel==='restricted'||item.permissionLevel===3||item.status==='blocked';return <article className="approval-card" key={item.id}><div className="approval-card-head"><div className="meta-row"><Badge tone={item.riskLevel}>{item.riskLevel} risk</Badge><Badge tone={blocked?'restricted':item.status}>{blocked?'blocked':item.status}</Badge></div><span>{item.confidence}% confidence</span></div><h2>{item.title}</h2><p className="approval-agent">{agents.find(agent=>agent.id===item.agentId)?.name||'local helper'} · {new Date(item.createdAt).toLocaleString()}</p><div className="approval-card-copy"><div><b>Proposed action</b><p>{item.editedAction||item.proposedAction}</p></div><div><b>Why it needs review</b><p>{item.reason}</p></div></div>{item.rejectionReason&&<p className="rejection-note"><b>Rejection note:</b> {item.rejectionReason}</p>}<div className="approval-card-footer"><small>{riskExplanation[item.riskLevel]}</small><button onClick={()=>{setSelectedId(item.id);scrollTo({top:0,behavior:'smooth'})}}>Approve, edit, or reject</button></div></article>}):<EmptyState title="Nothing needs review" text="When a draft needs your decision, it will wait here. Restricted actions remain blocked."/>}</div>
 </div>
}
