import { useEffect, useState } from 'react'
import type { Approval } from '../types'
import { agents } from '../data/agents'
import { Badge } from '../components/Badge'
import { EmptyState } from '../components/EmptyState'
import { PermissionGuide } from '../components/PermissionGuide'

export function ApprovalsPage({approvals,update}:{approvals:Approval[];update:(id:string,updates:Partial<Approval>)=>void}){
 const pending=approvals.filter(a=>a.status==='pending'||a.status==='edited');const [selectedId,setSelectedId]=useState<string|null>(null);const selected=approvals.find(a=>a.id===selectedId)
 const [action,setAction]=useState('');const [reason,setReason]=useState('')
 useEffect(()=>{setAction(selected?.proposedAction||'');setReason(selected?.rejectionReason||'')},[selectedId,selected?.proposedAction,selected?.rejectionReason])
 const actionable=selected&&(selected.status==='pending'||selected.status==='edited')
 return <div className="page"><header className="topbar"><div><p className="eyebrow">HUMAN IN CONTROL</p><h1>Approval queue</h1><p>Inspect and edit local previews. Approval never triggers an external action.</p></div><Badge tone="warning">{pending.length} pending</Badge></header><PermissionGuide/>
  {selected&&<section className="approval-detail"><button className="close-panel" aria-label="Close approval detail" onClick={()=>setSelectedId(null)}>×</button><div className="meta-row"><Badge tone={selected.riskLevel}>{selected.riskLevel} risk</Badge><Badge tone="warning">Level {selected.permissionLevel??2} · approval required</Badge><Badge tone={selected.status}>{selected.status}</Badge></div><h2>{selected.title}</h2><p>{selected.reason}</p><label>Editable proposed action<textarea value={action} disabled={!actionable} onChange={e=>setAction(e.target.value)}/></label><div className="payload-preview"><b>Proposed payload / action preview</b><pre>{selected.payloadPreview||JSON.stringify({mode:'local-preview',action:selected.proposedAction,externalExecution:false},null,2)}</pre></div><label>Rejection reason<input value={reason} disabled={!actionable} onChange={e=>setReason(e.target.value)} placeholder="Required before rejection"/></label><div className="detail-actions"><button disabled={!actionable} onClick={()=>update(selected.id,{proposedAction:action,editedAction:action,status:'edited'})}>Save local edit</button><button disabled={!actionable||!reason.trim()} onClick={()=>update(selected.id,{status:'rejected',rejectionReason:reason,decidedAt:new Date().toISOString()})}>Reject with reason</button><button className="primary" disabled={!actionable} onClick={()=>update(selected.id,{status:'approved',decidedAt:new Date().toISOString()})}>Approve locally →</button></div>{selected.decidedAt&&<small>Decision recorded {new Date(selected.decidedAt).toLocaleString()} · local state only.</small>}<div className="level3-warning"><b>Level 3 remains blocked</b><span>Payments, reconciliation, tax, deletion, irreversible actions, auto-deploy, and autonomous production changes cannot be approved here.</span></div></section>}
  <div className="approval-list">{approvals.length?approvals.map(a=><article className="approval-card" key={a.id}><div className="approval-main"><div className="approval-title"><span className="activity-icon">!</span><div><div className="meta-row"><Badge tone={a.riskLevel}>{a.riskLevel} risk</Badge><Badge tone={a.status}>{a.status}</Badge><Badge>Level {a.permissionLevel??2}</Badge><Badge>Simulated locally</Badge>{a.sourceOutputId&&<Badge>Linked report</Badge>}</div><h2>{a.title}</h2><p>{agents.find(x=>x.id===a.agentId)?.name} · {new Date(a.createdAt).toLocaleString()}</p></div></div><dl><div><dt>Proposed preview</dt><dd>{a.proposedAction}</dd></div><div><dt>Reason</dt><dd>{a.reason}</dd></div></dl></div><div className="confidence"><span>Confidence</span><strong>{a.confidence}%</strong><div><i style={{width:`${a.confidence}%`}}/></div></div><div className="approval-actions"><button className="primary" onClick={()=>setSelectedId(a.id)}>Review details →</button><small>{a.decidedAt?`Decided ${new Date(a.decidedAt).toLocaleString()}`:'No external service contacted.'}</small></div></article>):<EmptyState title="No local approvals yet" text="Level 2 proposals create local approval previews here. Level 3 actions always remain blocked."/>}</div></div>
}
