import { useEffect, useMemo, useState } from 'react'
import type { BusinessProfile, ConnectionDraftBundle, FounderMatch, FounderProfile } from '../types'
import { Badge } from '../components/Badge'
import { getFounderMatches, saveFounderMatches, updateFounderMatch } from '../services/communityService'

type Filter='all'|'industry'|'stage'|'goal'|'saved'|'drafted'
export function CommunityPage({profile,founderProfile,draftConnection,openReports,openApprovals}:{profile:BusinessProfile;founderProfile:FounderProfile;draftConnection:(match:FounderMatch)=>ConnectionDraftBundle;openReports:()=>void;openApprovals:()=>void}){
 const [matches,setMatches]=useState<FounderMatch[]>(()=>getFounderMatches());const [filter,setFilter]=useState<Filter>('all');const [draft,setDraft]=useState<ConnectionDraftBundle|null>(null);const [copied,setCopied]=useState(false)
 useEffect(()=>{saveFounderMatches(matches)},[matches])
 const relevant=(match:FounderMatch)=>match.industry.toLowerCase().includes(profile.industry.toLowerCase())||match.tags.some(tag=>founderProfile.currentPriorities.join(' ').toLowerCase().includes(tag.replace('-',' ')))
 const shown=useMemo(()=>matches.filter(match=>match.status!=='dismissed'&&(filter==='all'||filter==='saved'&&match.status==='saved'||filter==='drafted'&&match.status==='drafted'||filter==='industry'&&relevant(match)||filter==='stage'&&match.stage.toLowerCase().includes(profile.stage.toLowerCase().split(' ')[0])||filter==='goal'&&match.goals.some(goal=>founderProfile.currentPriorities.some(priority=>goal.toLowerCase().includes(priority.toLowerCase())||priority.toLowerCase().includes(goal.toLowerCase()))))),[matches,filter,profile.stage,profile.industry,founderProfile.currentPriorities])
 const change=(id:string,status:FounderMatch['status'])=>setMatches(items=>updateFounderMatch(items,id,status))
 const create=(match:FounderMatch)=>{const bundle=draftConnection(match);setDraft(bundle);change(match.id,'drafted');scrollTo({top:0,behavior:'smooth'})}
 const copy=async()=>{if(!draft)return;try{await navigator.clipboard?.writeText(draft.output.copyableText||draft.output.fullOutput);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}}
 const saved=matches.filter(match=>match.status==='saved')
 return <div className="page community-page"><header className="topbar friendly-topbar"><div><p className="eyebrow">FOUNDER COMMUNITY</p><h1>Who could you connect with next?</h1><p>Explore fictional founder matches and prepare a thoughtful introduction.</p></div><Badge tone="live">Opt-in · local only</Badge></header>
  <section className="community-intro"><span>◎</span><div><h2>Suggested connections, not a real network</h2><p>These profiles are fictional examples generated for the MVP. SmallBiz Agent does not scrape people, access contact details, or send outreach. You choose what to save, dismiss, or draft.</p></div></section>
  {draft&&<section className="connection-draft-result"><div className="result-check">✓</div><div><span className="eyebrow">DRAFT READY</span><h2>{draft.output.title}</h2><p>{draft.output.summary}</p><div className="draft-sections"><section><b>Recommended approach</b><p>{draft.output.keyFindings?.[0]?.replace('Recommended approach: ','')}</p></section><section><b>Draft message</b><pre>{draft.draft.message}</pre></section><section><b>Short version</b><p>{draft.draft.shortVersion}</p></section><section><b>Call to action</b><p>{draft.draft.callToAction}</p></section></div><div className="community-safety"><b>Preview only · nothing was sent</b><span>No email, DM, contact lookup, scraping, or external action occurred. Future outreach remains approval-gated.</span></div><div className="draft-actions"><button onClick={copy}>{copied?'Draft copied':'Copy draft'}</button><button onClick={openReports}>Open saved report</button><button onClick={openApprovals}>Review approval preview</button><button onClick={()=>setDraft(null)}>Close</button></div></div></section>}
  <div className="community-filters">{([['all','All matches'],['industry','My industry'],['stage','My stage'],['goal','My goals'],['saved','Saved'],['drafted','Drafted']] as [Filter,string][]).map(([id,label])=><button className={filter===id?'active':''} key={id} onClick={()=>setFilter(id)}>{label}</button>)}</div>
  {saved.length>0&&filter!=='saved'&&<section className="saved-connections"><div className="simple-section-title"><h2>Saved connections</h2><button onClick={()=>setFilter('saved')}>View all</button></div><div>{saved.slice(0,3).map(match=><article key={match.id}><div><b>{match.name}</b><small>{match.businessName} · {match.industry}</small></div><button onClick={()=>create(match)}>Draft message</button><button onClick={()=>change(match.id,'suggested')}>Unsave</button></article>)}</div></section>}
  <section><div className="simple-section-title"><h2>{filter==='saved'?'Saved founder matches':'Suggested founder matches'}</h2><Badge>{shown.length} fictional profiles</Badge></div>{shown.length?<div className="founder-match-grid">{shown.map(match=><article key={match.id}><header><div className="match-avatar">{match.name.split(' ').slice(0,2).map(word=>word[0]).join('')}</div><div><h3>{match.name}</h3><p>{match.businessName}</p></div><strong>{match.relevanceScore}% fit</strong></header><div className="match-meta"><span>{match.industry}</span><span>{match.stage}</span><span>{match.location}</span></div><section><b>Why this could be useful</b><p>{match.matchReason}</p></section><section><b>A friendly way to start</b><p>{match.suggestedApproach}</p></section><div className="match-tags">{match.tags.map(tag=><span key={tag}>#{tag}</span>)}</div><footer>{match.status==='saved'?<button onClick={()=>change(match.id,'suggested')}>Saved ✓</button>:<button onClick={()=>change(match.id,'saved')}>Save</button>}<button className="primary" onClick={()=>create(match)}>Draft message</button><button onClick={()=>change(match.id,'dismissed')}>Dismiss</button></footer></article>)}</div>:<div className="community-empty"><b>No matches in this view</b><p>Try another filter. Dismissed suggestions stay hidden on this device.</p><button onClick={()=>setFilter('all')}>Show all matches</button></div>}</section>
  <section className="community-boundary"><b>Always blocked in this MVP</b><span>Automatic sending, scraping, mass outreach, buying contact lists, external integrations, and irreversible actions remain unavailable.</span></section>
 </div>
}
