import { useState } from 'react'
import type { AgenticExecutionBundle, Approval, AgentOutput, BusinessProfile, CommandHistoryItem, CommandRouteSuggestion, EndOfDayReviewInput, FounderProfile, GoalOrchestratorBundle, MockAgentResult, OperatorNotice, ProjectActionItem, ProjectMilestone, ProjectWorkspaceProject, Workflow } from '../types'
import { agents } from '../data/agents'
import { Badge } from '../components/Badge'
import { recommendWorkflows } from '../services/workflowRecommendations'
import { addCommandHistory, getCommandHistory, routeCommand } from '../services/commandRouter'
import { deriveDailyFocus } from '../services/dailyFocusService'
import { EndOfDayReview } from '../components/EndOfDayReview'
import { GoalOrchestratorPanel } from '../components/GoalOrchestratorPanel'

const examples=['Plan my week','Turn feedback into tasks','Write a founder post','Prepare a coding prompt','Review invoices','Research competitors','Help me reply to a customer']
interface Props {operatorNotices:OperatorNotice[];timeSaved:{todayMinutes:number;weekMinutes:number;emailsReviewed:number;draftsPrepared:number;meetingsOrganised:number;decisionsEscalated:number};updateOperatorNotice:(id:string,status:OperatorNotice['status'])=>void;profile:BusinessProfile;founderProfile:FounderProfile;workflows:Workflow[];reports:AgentOutput[];approvals:Approval[];projects:ProjectWorkspaceProject[];projectActions:ProjectActionItem[];projectMilestones:ProjectMilestone[];saveDailyReview:(input:EndOfDayReviewInput)=>AgentOutput;markFocusActionDone:(id:string)=>void;run:(id:string,command?:string)=>void;go:(page:'workflows'|'approvals'|'reports'|'agents'|'workspace'|'community')=>void;submitPrompt:(prompt:string)=>MockAgentResult;promptResult:MockAgentResult|null;runGoal:(input:string,projectId?:string)=>GoalOrchestratorBundle|null;runAgenticExecution:(bundle:GoalOrchestratorBundle)=>AgenticExecutionBundle}

export function HomePage({operatorNotices,timeSaved,updateOperatorNotice,profile,founderProfile,workflows,reports,approvals,projects,projectActions,projectMilestones,saveDailyReview,markFocusActionDone,run,go,runGoal,runAgenticExecution}:Props){
 const [prompt,setPrompt]=useState('');const [suggestion,setSuggestion]=useState<CommandRouteSuggestion|null>(null);const [history,setHistory]=useState<CommandHistoryItem[]>(()=>getCommandHistory())
 const [focusProjectId,setFocusProjectId]=useState(projects.find(item=>!['Complete','Paused'].includes(item.status))?.id||projects[0]?.id||'')
 const pending=approvals.filter(item=>item.status==='pending');const recommended=recommendWorkflows(workflows,founderProfile);const openActions=projectActions.filter(item=>item.status!=='done');const blockedActions=projectActions.filter(item=>item.status==='blocked');const nextAction=openActions.find(item=>item.status==='doing')||openActions[0]
 const quickBuilds:Array<{label:string;icon:string;command:string;page?:'community'}>=[
  {label:'Build Business Plan',icon:'✦',command:'Help me build a simple business plan'},
  {label:'Review Gmail',icon:'✉',command:'Review my Gmail inbox and prepare safe replies'},
  {label:'Create Website',icon:'◎',command:'Help me plan and create a business website'},
  {label:'Run Ads',icon:'◉',command:'Help me prepare a safe draft ad campaign'},
  {label:'Market Research',icon:'⌕',command:'Research my market and ideal customers'},
  {label:'Financial Forecast',icon:'↗',command:'Create a simple financial forecast for my business'},
  {label:'Prepare Coding Prompt',icon:'⌁',command:'Prepare a clear coding prompt for my project'},
  {label:'Find Founder Connections',icon:'♡',command:'Find relevant founders I could connect with',page:'community'}
 ]
 const route=(command=prompt)=>{if(!command.trim())return;const next=routeCommand(command,founderProfile,agents,workflows);setPrompt(command);setSuggestion(next);setHistory(addCommandHistory(next))}
 const choose=(workflowId:string)=>{if(!suggestion)return;const workflow=workflows.find(item=>item.id===workflowId);if(!workflow)return;setSuggestion({...suggestion,recommendedWorkflowId:workflow.id,recommendedAgentId:workflow.assignedAgent,safetyNote:workflow.requiresApproval?'This creates a local draft and a review item. Nothing will be sent or changed.':'Nothing will be sent or changed. This only creates a local draft.',suggestedNextStep:`We’ll run ${workflow.name} using your original request and save the result.`})}
 const selectedWorkflow=workflows.find(item=>item.id===suggestion?.recommendedWorkflowId);const selectedAgent=agents.find(item=>item.id===suggestion?.recommendedAgentId)
 const dailyFocus=deriveDailyFocus(projects,projectActions,projectMilestones,approvals,reports,focusProjectId);const focusProject=projects.find(item=>item.id===dailyFocus.projectId);const focusAction=dailyFocus.topPriorities[0]
 return <div className="page home-page simple-home">
  <header className="welcome"><p>AI OPERATIONS PARTNER</p><h1>SmallBiz Agent gives small business owners their time back.</h1><span>It notices boring admin, prepares safe next actions, and escalates only the decisions that need you.</span></header>
  <section className="time-back-panel"><div><span className="eyebrow">TIME GIVEN BACK</span><h2>{Math.floor(timeSaved.todayMinutes/60)}h {timeSaved.todayMinutes%60}m saved today</h2><p>SmallBiz Agent prepares the work. You stay in control.</p></div><div className="time-metrics"><b>{Math.floor(timeSaved.weekMinutes/60)}h {timeSaved.weekMinutes%60}m<small>this week</small></b><b>{timeSaved.emailsReviewed}<small>emails reviewed</small></b><b>{timeSaved.draftsPrepared}<small>drafts prepared</small></b><b>{timeSaved.meetingsOrganised}<small>meetings organised</small></b><b>{timeSaved.decisionsEscalated}<small>decisions escalated</small></b></div></section>
  <section className="admin-review"><div className="simple-section-title"><div><span className="eyebrow">TODAY’S ADMIN REVIEW</span><h2>Prepared next actions</h2></div><button onClick={()=>go('approvals')}>Open decisions</button></div><div className="notice-grid">{operatorNotices.filter(n=>n.status!=='dismissed').slice(0,5).map(notice=><article key={notice.id} className="operator-notice"><div className="meta-row"><Badge tone={notice.riskLevel}>{notice.category}</Badge><Badge tone={notice.permissionLevel>=2?'warning':'live'}>Level {notice.permissionLevel}</Badge><Badge>{notice.estimatedTimeSavedMinutes}m saved</Badge></div><h3>{notice.title}</h3><p>{notice.summary}</p><div><button onClick={()=>notice.permissionLevel>=2?go('approvals'):updateOperatorNotice(notice.id,'completed')}>{notice.permissionLevel>=2?'View approval':'Review'}</button><button onClick={()=>updateOperatorNotice(notice.id,'drafted')}>{notice.suggestedAction.includes('Draft')?'Draft':'Draft'}</button><button onClick={()=>updateOperatorNotice(notice.id,'dismissed')}>Dismiss</button></div></article>)}</div></section>
  <section className="founder-focus"><div className="focus-head"><div><span className="eyebrow">TODAY’S FOCUS</span><h2>{dailyFocus.focusMessage}</h2></div>{projects.length>1&&<select aria-label="Choose focus project" value={focusProjectId} onChange={event=>{setFocusProjectId(event.target.value)}}>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select>}</div>{!focusProject?<div className="focus-empty"><b>Create your first project</b><p>Your AI team can plan the day around a project, its actions, milestones, reports, and approvals.</p><button onClick={()=>go('workspace')}>Create a project</button></div>:<><div className="focus-priority-grid"><section><h3>Top priorities</h3>{dailyFocus.topPriorities.length?dailyFocus.topPriorities.map((item,index)=><div className="focus-line" key={item.id}><span>{index+1}</span><div><b>{item.title}</b><small>{item.priority} priority · {item.status==='blocked'?'stuck':item.status}</small></div></div>):<p>No actions yet. Ask the AI team to create your first plan.</p>}</section><section><h3>Watch today</h3><p><b>{dailyFocus.stuckItems.length} stuck</b> {dailyFocus.stuckItems[0]?.title||'No blockers marked.'}</p><p><b>Milestone</b> {dailyFocus.nextMilestone?.title||'No milestone active yet.'}</p><p><b>{dailyFocus.pendingApprovals.length} approvals</b> {dailyFocus.pendingApprovals[0]?.title||'Nothing waiting.'}</p><p><b>Latest report</b> {dailyFocus.latestReport?.title||'No reports yet.'}</p></section></div><div className="daily-focus-mode"><div><span className="eyebrow">DAILY FOCUS MODE</span><h3>{focusProject.name}</h3><p>{focusProject.ownerGoal||focusProject.description||'Add a goal so your AI team knows what matters.'}</p>{focusAction&&<p><b>Next recommended action:</b> {focusAction.title}</p>}<small>Why it matters: this is the strongest unfinished signal from your local project board.</small></div><div className="focus-buttons"><button onClick={()=>run('daily',`Help me focus on ${focusProject.name}: ${focusAction?.title||'create the next actions'}`)}>Help me do this</button><button onClick={()=>run('daily',`Turn ${focusProject.name} into a simple checklist`)}>Turn into checklist</button><button onClick={()=>go('agents')}>Ask {agents.find(agent=>agent.id===dailyFocus.suggestedAgentId)?.name||'the right agent'}</button>{focusAction&&<button onClick={()=>markFocusActionDone(focusAction.id)}>Mark done</button>}</div></div><p className="focus-safety">Your AI operations partner can read, organise, recommend, and prepare drafts here. It cannot spend money, publish, launch ads, send emails, create issues, or change external systems. Level 2 needs approval; Level 3 stays blocked.</p></>}</section>
  <GoalOrchestratorPanel projects={projects} runGoal={runGoal} runAgenticExecution={runAgenticExecution} openReports={()=>go('reports')} openApprovals={()=>go('approvals')}/>
  <EndOfDayReview projectId={focusProjectId||undefined} save={saveDailyReview}/><form className="help-command smart-command" onSubmit={event=>{event.preventDefault();route()}}><label htmlFor="main-help">Ask your AI team anything</label><div><input id="main-help" value={prompt} onChange={event=>setPrompt(event.target.value)} placeholder="Ask your AI team anything…"/><button type="submit" aria-label="Send request">→</button></div><div className="command-examples">{examples.map(example=><button type="button" key={example} onClick={()=>{setPrompt(example);route(example)}}>{example}</button>)}</div><small>Private local demo · nothing is sent or changed.</small></form>
  {suggestion&&selectedWorkflow&&selectedAgent&&<section className={`route-suggestion ${suggestion.blocked?'blocked-result':''}`}><div className="route-heading"><div><span className="eyebrow">{suggestion.blocked?'BLOCKED IN MVP':'RECOMMENDED FOR YOU'}</span><h2>{suggestion.blocked?'Level 3 action blocked':'Here’s the simplest next step'}</h2></div><Badge tone={suggestion.blocked?'restricted':'live'}>{suggestion.blocked?'Blocked':'Ready'}</Badge></div><div className="route-picks"><div><small>BEST HELPER</small><b>{selectedAgent.name}</b></div><div><small>{suggestion.blocked?'STATUS':'BEST NEXT STEP'}</small><b>{suggestion.blocked?'No workflow can run this':selectedWorkflow.name}</b></div></div><dl><div><dt>Why this fits</dt><dd>{suggestion.reason}</dd></div><div><dt>{suggestion.blocked?'Safer alternative':'What will happen'}</dt><dd>{suggestion.suggestedNextStep}</dd></div><div><dt>Safety note</dt><dd>{suggestion.safetyNote}</dd></div></dl>{!suggestion.blocked&&<label className="workflow-choice">Choose another workflow<select value={selectedWorkflow.id} onChange={event=>choose(event.target.value)}>{workflows.filter(item=>item.riskLevel!=='restricted').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<div className="route-actions">{!suggestion.blocked&&<button className="primary" onClick={()=>run(selectedWorkflow.id,suggestion.originalCommand)}>Run this workflow</button>}<button onClick={()=>{setSuggestion(null);setTimeout(()=>document.getElementById('main-help')?.focus(),0)}}>{suggestion.blocked?'Edit request':'Edit my request'}</button></div></section>}
  {!suggestion&&<section className="build-today"><div className="simple-section-title"><h2>What would you like to make?</h2><button onClick={()=>go('workspace')}>Open guided Builder</button></div><div className="simple-quick-grid">{quickBuilds.map((item,i)=><button key={item.label} onClick={()=>{if(item.page){go(item.page);return}setPrompt(item.command);route(item.command)}}><span>{item.icon}</span><b>{item.label}</b><small>{['Plan it step by step','Prioritise inbox safely','Shape your online home','Draft before you spend','Understand your customers','See the numbers simply','Brief your coding tool','Meet useful founder peers'][i]}</small></button>)}</div></section>}
  <section className="ai-team-preview"><div className="simple-section-title"><h2>Meet your AI team</h2><button onClick={()=>go('agents')}>View all</button></div><div>{agents.slice(0,5).map((agent,index)=><button key={agent.id} onClick={()=>go('agents')}><span className={`agent-face face-${index}`}>{['✦','♡','◉','⌁','◎'][index]}</span><b>{agent.name}</b><small>{agent.role}</small></button>)}</div></section>
  {history.length>0&&<section className="recent-requests"><div className="simple-section-title"><h2>Recent requests</h2></div><div>{history.slice(0,4).map(item=><button key={item.id} onClick={()=>{setPrompt(item.command);route(item.command)}}><span>↗</span>{item.command}</button>)}</div></section>}
  {projects.length>0&&<section className="workspace-signals"><span>{openActions.length} open actions</span><span>{blockedActions.length} stuck</span><span>{projectActions.filter(item=>item.status==='done').length} done</span>{nextAction&&<b>Next: {nextAction.title}</b>}<button onClick={()=>go('workspace')}>Open project board</button></section>}
  <section className="calm-panel workspace-preview"><div className="simple-section-title"><h2>Workspace</h2><button onClick={()=>go('workspace')}>Open</button></div>{projects.length?projects.slice(0,3).map(project=><button className="simple-list-item" key={project.id} onClick={()=>go('workspace')}><span>▦</span><div><b>{project.name}</b><small>{project.status} · {project.nextActions.filter(action=>!action.done).length} next steps</small></div></button>):<p className="friendly-empty">Create a project to keep your business ideas, saved work, notes, and next steps in one place.</p>}</section><div className="simple-dashboard"><section className="calm-panel"><div className="simple-section-title"><h2>Needs review</h2><button onClick={()=>go('approvals')}>See all</button></div>{pending.length?pending.slice(0,2).map(item=><button className="simple-list-item" key={item.id} onClick={()=>go('approvals')}><span>!</span><div><b>{item.title}</b><small>{item.reason}</small></div></button>):<p className="friendly-empty">You’re all caught up. Important actions will wait here for you.</p>}</section><section className="calm-panel"><div className="simple-section-title"><h2>Recent saved work</h2><button onClick={()=>go('reports')}>See all</button></div>{reports.length?reports.slice(0,3).map(item=><button className="simple-list-item" key={item.id} onClick={()=>go('reports')}><span>✓</span><div><b>{item.title}</b><small>{agents.find(agent=>agent.id===item.agentId)?.name} · {new Date(item.createdAt).toLocaleDateString()}</small></div></button>):<p className="friendly-empty">Nothing saved yet. Ask for help above to create your first piece of work.</p>}</section></div>
  <section className="calm-panel priorities-panel"><div className="simple-section-title"><h2>Current focus</h2><Badge tone="live">For {profile.businessName}</Badge></div>{founderProfile.goals.map((goal,index)=><div className="priority" key={goal}><span>{index+1}</span><div><b>{goal}</b><small>{index===0?`Suggested next: ${recommended[0]?.name||'Plan my day'}`:(founderProfile.projects[0]||profile.biggestChallenge)}</small></div></div>)}</section>
 </div>
}
