import { useState } from 'react'
import type { Approval, AgentOutput, BusinessProfile, CommandHistoryItem, CommandRouteSuggestion, EndOfDayReviewInput, FounderProfile, MockAgentResult, ProjectActionItem, ProjectMilestone, ProjectWorkspaceProject, Workflow } from '../types'
import { agents } from '../data/agents'
import { Badge } from '../components/Badge'
import { recommendWorkflows } from '../services/workflowRecommendations'
import { addCommandHistory, getCommandHistory, routeCommand } from '../services/commandRouter'
import { deriveDailyFocus } from '../services/dailyFocusService'
import { EndOfDayReview } from '../components/EndOfDayReview'

const examples=['Plan my week','Turn feedback into tasks','Write a founder post','Prepare a coding prompt','Review invoices','Research competitors','Help me reply to a customer']
const quickGoals:Record<string,string[]>={'Get organised':['daily'],'Find customers':['marketing','research'],'Improve product/service':['vexis','research'],'Create content/marketing':['marketing'],'Handle admin/finance':['invoice','daily'],'Research ideas/tools':['research'],'Build software/features':['github','vexis']}
interface Props {profile:BusinessProfile;founderProfile:FounderProfile;workflows:Workflow[];reports:AgentOutput[];approvals:Approval[];projects:ProjectWorkspaceProject[];projectActions:ProjectActionItem[];projectMilestones:ProjectMilestone[];saveDailyReview:(input:EndOfDayReviewInput)=>AgentOutput;markFocusActionDone:(id:string)=>void;run:(id:string,command?:string)=>void;go:(page:'workflows'|'approvals'|'reports'|'agents'|'workspace')=>void;submitPrompt:(prompt:string)=>MockAgentResult;promptResult:MockAgentResult|null}

export function HomePage({profile,founderProfile,workflows,reports,approvals,projects,projectActions,projectMilestones,saveDailyReview,markFocusActionDone,run,go}:Props){
 const [prompt,setPrompt]=useState('');const [suggestion,setSuggestion]=useState<CommandRouteSuggestion|null>(null);const [history,setHistory]=useState<CommandHistoryItem[]>(()=>getCommandHistory())
 const [focusProjectId,setFocusProjectId]=useState(projects.find(item=>!['Complete','Paused'].includes(item.status))?.id||projects[0]?.id||'')
 const pending=approvals.filter(item=>item.status==='pending');const recommended=recommendWorkflows(workflows,founderProfile);const preferredIds=new Set(founderProfile.goals.flatMap(goal=>quickGoals[goal]||[]));const openActions=projectActions.filter(item=>item.status!=='done');const blockedActions=projectActions.filter(item=>item.status==='blocked');const nextAction=openActions.find(item=>item.status==='doing')||openActions[0]
 const hour=new Date().getHours();const greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening'
 const route=(command=prompt)=>{if(!command.trim())return;const next=routeCommand(command,founderProfile,agents,workflows);setPrompt(command);setSuggestion(next);setHistory(addCommandHistory(next))}
 const choose=(workflowId:string)=>{if(!suggestion)return;const workflow=workflows.find(item=>item.id===workflowId);if(!workflow)return;setSuggestion({...suggestion,recommendedWorkflowId:workflow.id,recommendedAgentId:workflow.assignedAgent,safetyNote:workflow.requiresApproval?'This creates a local draft and a review item. Nothing will be sent or changed.':'Nothing will be sent or changed. This only creates a local draft.',suggestedNextStep:`We’ll run ${workflow.name} using your original request and save the result.`})}
 const selectedWorkflow=workflows.find(item=>item.id===suggestion?.recommendedWorkflowId);const selectedAgent=agents.find(item=>item.id===suggestion?.recommendedAgentId)
 const dailyFocus=deriveDailyFocus(projects,projectActions,projectMilestones,approvals,reports,focusProjectId);const focusProject=projects.find(item=>item.id===dailyFocus.projectId);const focusAction=dailyFocus.topPriorities[0]
 return <div className="page home-page simple-home">
  <header className="welcome"><p>{new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</p><h1>{greeting}, {founderProfile.name}. What can we help with?</h1><span>{profile.businessName} · {founderProfile.businessType}</span></header>
  <section className="founder-focus"><div className="focus-head"><div><span className="eyebrow">TODAY’S FOCUS</span><h2>{dailyFocus.focusMessage}</h2></div>{projects.length>1&&<select aria-label="Choose focus project" value={focusProjectId} onChange={event=>{setFocusProjectId(event.target.value)}}>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select>}</div>{!focusProject?<div className="focus-empty"><b>Create your first project</b><p>Your AI team can plan the day around a project, its actions, milestones, reports, and approvals.</p><button onClick={()=>go('workspace')}>Create a project</button></div>:<><div className="focus-priority-grid"><section><h3>Top priorities</h3>{dailyFocus.topPriorities.length?dailyFocus.topPriorities.map((item,index)=><div className="focus-line" key={item.id}><span>{index+1}</span><div><b>{item.title}</b><small>{item.priority} priority · {item.status==='blocked'?'stuck':item.status}</small></div></div>):<p>No actions yet. Ask the AI team to create your first plan.</p>}</section><section><h3>Watch today</h3><p><b>{dailyFocus.stuckItems.length} stuck</b> {dailyFocus.stuckItems[0]?.title||'No blockers marked.'}</p><p><b>Milestone</b> {dailyFocus.nextMilestone?.title||'No milestone active yet.'}</p><p><b>{dailyFocus.pendingApprovals.length} approvals</b> {dailyFocus.pendingApprovals[0]?.title||'Nothing waiting.'}</p><p><b>Latest report</b> {dailyFocus.latestReport?.title||'No reports yet.'}</p></section></div><div className="daily-focus-mode"><div><span className="eyebrow">DAILY FOCUS MODE</span><h3>{focusProject.name}</h3><p>{focusProject.ownerGoal||focusProject.description||'Add a goal so your AI team knows what matters.'}</p>{focusAction&&<p><b>Next recommended action:</b> {focusAction.title}</p>}<small>Why it matters: this is the strongest unfinished signal from your local project board.</small></div><div className="focus-buttons"><button onClick={()=>run('daily',`Help me focus on ${focusProject.name}: ${focusAction?.title||'create the next actions'}`)}>Help me do this</button><button onClick={()=>run('daily',`Turn ${focusProject.name} into a simple checklist`)}>Turn into checklist</button><button onClick={()=>go('agents')}>Ask {agents.find(agent=>agent.id===dailyFocus.suggestedAgentId)?.name||'the right agent'}</button>{focusAction&&<button onClick={()=>markFocusActionDone(focusAction.id)}>Mark done</button>}</div></div><p className="focus-safety">Your AI team can recommend and draft here. It cannot spend money, publish, launch ads, send emails, create issues, or change external systems. Level 2 needs approval; Level 3 stays blocked.</p></>}</section>
  <EndOfDayReview projectId={focusProjectId||undefined} save={saveDailyReview}/><form className="help-command smart-command" onSubmit={event=>{event.preventDefault();route()}}><label htmlFor="main-help">Tell your AI team what you need</label><div><input id="main-help" value={prompt} onChange={event=>setPrompt(event.target.value)} placeholder="e.g. Write a founder post about my product"/><button type="submit">Find the best help</button></div><div className="command-examples">{examples.map(example=><button type="button" key={example} onClick={()=>{setPrompt(example);route(example)}}>{example}</button>)}</div><small>Nothing is sent or changed. Your request stays in this browser.</small></form>
  {suggestion&&selectedWorkflow&&selectedAgent&&<section className="route-suggestion"><div className="route-heading"><div><span className="eyebrow">RECOMMENDED FOR YOU</span><h2>Here’s the simplest next step</h2></div><Badge tone="live">Ready</Badge></div><div className="route-picks"><div><small>BEST HELPER</small><b>{selectedAgent.name}</b></div><div><small>BEST NEXT STEP</small><b>{selectedWorkflow.name}</b></div></div><dl><div><dt>Why this fits</dt><dd>{suggestion.reason}</dd></div><div><dt>What will happen</dt><dd>{suggestion.suggestedNextStep}</dd></div><div><dt>Safety note</dt><dd>{suggestion.safetyNote}</dd></div></dl><label className="workflow-choice">Choose another workflow<select value={selectedWorkflow.id} onChange={event=>choose(event.target.value)}>{workflows.filter(item=>item.riskLevel!=='restricted').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="route-actions"><button className="primary" onClick={()=>run(selectedWorkflow.id,suggestion.originalCommand)}>Run this workflow</button><button onClick={()=>{setSuggestion(null);setTimeout(()=>document.getElementById('main-help')?.focus(),0)}}>Edit my request</button></div></section>}
  {!suggestion&&<section><div className="simple-section-title"><h2>Recommended for your goals</h2><button onClick={()=>go('workflows')}>See everything</button></div><div className="simple-quick-grid">{recommended.slice(0,6).map((item,i)=><button key={item.id} onClick={()=>run(item.id)}>{preferredIds.has(item.id)&&<em>For your goals</em>}<span>{['☀','♡','✎','⌁','▣','⌕'][i]}</span><b>{item.name}</b></button>)}</div></section>}
  {history.length>0&&<section className="recent-requests"><div className="simple-section-title"><h2>Recent requests</h2></div><div>{history.slice(0,4).map(item=><button key={item.id} onClick={()=>{setPrompt(item.command);route(item.command)}}><span>↗</span>{item.command}</button>)}</div></section>}
  {projects.length>0&&<section className="workspace-signals"><span>{openActions.length} open actions</span><span>{blockedActions.length} stuck</span><span>{projectActions.filter(item=>item.status==='done').length} done</span>{nextAction&&<b>Next: {nextAction.title}</b>}<button onClick={()=>go('workspace')}>Open project board</button></section>}
  <section className="calm-panel workspace-preview"><div className="simple-section-title"><h2>Workspace</h2><button onClick={()=>go('workspace')}>Open</button></div>{projects.length?projects.slice(0,3).map(project=><button className="simple-list-item" key={project.id} onClick={()=>go('workspace')}><span>▦</span><div><b>{project.name}</b><small>{project.status} · {project.nextActions.filter(action=>!action.done).length} next steps</small></div></button>):<p className="friendly-empty">Create a project to keep your business ideas, saved work, notes, and next steps in one place.</p>}</section><div className="simple-dashboard"><section className="calm-panel"><div className="simple-section-title"><h2>Needs review</h2><button onClick={()=>go('approvals')}>See all</button></div>{pending.length?pending.slice(0,2).map(item=><button className="simple-list-item" key={item.id} onClick={()=>go('approvals')}><span>!</span><div><b>{item.title}</b><small>{item.reason}</small></div></button>):<p className="friendly-empty">You’re all caught up. Important actions will wait here for you.</p>}</section><section className="calm-panel"><div className="simple-section-title"><h2>Recent saved work</h2><button onClick={()=>go('reports')}>See all</button></div>{reports.length?reports.slice(0,3).map(item=><button className="simple-list-item" key={item.id} onClick={()=>go('reports')}><span>✓</span><div><b>{item.title}</b><small>{agents.find(agent=>agent.id===item.agentId)?.name} · {new Date(item.createdAt).toLocaleDateString()}</small></div></button>):<p className="friendly-empty">Nothing saved yet. Ask for help above to create your first piece of work.</p>}</section></div>
  <section className="calm-panel priorities-panel"><div className="simple-section-title"><h2>Current focus</h2><Badge tone="live">For {profile.businessName}</Badge></div>{founderProfile.goals.map((goal,index)=><div className="priority" key={goal}><span>{index+1}</span><div><b>{goal}</b><small>{index===0?`Suggested next: ${recommended[0]?.name||'Plan my day'}`:(founderProfile.projects[0]||profile.biggestChallenge)}</small></div></div>)}</section>
 </div>
}
