import { useMemo, useState } from 'react'
import type { AgentOutput } from '../types'
import { agents } from '../data/agents'
import { Badge } from '../components/Badge'
import { EmptyState } from '../components/EmptyState'

interface Props{reports:AgentOutput[];rate:(id:string,r:AgentOutput['usefulnessRating'])=>void;highlightedReportId?:string;onRunRecommended:()=>void}
export function ReportsPage({reports,rate,highlightedReportId,onRunRecommended}:Props){
 const [search,setSearch]=useState('');const [agentFilter,setAgentFilter]=useState('all');const [tagFilter,setTagFilter]=useState('all')
 const copy=(text:string)=>navigator.clipboard?.writeText(text)
 const agentIds=useMemo(()=>[...new Set(reports.map(r=>r.agentId))],[reports]);const tags=useMemo(()=>[...new Set(reports.flatMap(r=>r.tags))].sort(),[reports])
 const filtered=reports.filter(r=>(agentFilter==='all'||r.agentId===agentFilter)&&(tagFilter==='all'||r.tags.includes(tagFilter))&&(!search.trim()||`${r.title} ${r.summary} ${r.fullOutput} ${r.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())))
 return <div className="page"><header className="topbar"><div><p className="eyebrow">LOCAL KNOWLEDGE</p><h1>Outputs & reports</h1><p>Search, filter, inspect, copy, and rate everything your local team produced.</p></div><Badge>{reports.length} reports</Badge></header>
  <section className="report-filters"><label>Search reports<input aria-label="Search reports" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title, summary, output, or tag"/></label><label>Agent<select aria-label="Filter by agent" value={agentFilter} onChange={e=>setAgentFilter(e.target.value)}><option value="all">All agents</option>{agentIds.map(id=><option value={id} key={id}>{agents.find(a=>a.id===id)?.name||id}</option>)}</select></label><label>Tag<select aria-label="Filter by tag" value={tagFilter} onChange={e=>setTagFilter(e.target.value)}><option value="all">All tags</option>{tags.map(tag=><option value={tag} key={tag}>{tag}</option>)}</select></label><Badge tone={filtered.length?'live':'neutral'}>{filtered.length} shown</Badge></section>
  {filtered.length?<div className="reports-list">{filtered.map(r=><details className={`report-card ${r.id===highlightedReportId?'highlighted':''}`} key={r.id}><summary><div><div className="meta-row"><Badge tone="live">{r.source||'workflow'}</Badge>{r.tags.map((t,i)=><Badge key={`${t}-${i}`}>{t}</Badge>)}{r.permissionLevel!==undefined&&<Badge>Level {r.permissionLevel}</Badge>}{r.estimatedCostMode&&<Badge>{r.estimatedCostMode} future mode</Badge>}{r.skillStatus&&<Badge tone="warning">{r.skillStatus.replace('_',' ')}</Badge>}{r.approvalNeeded&&<Badge tone="warning">Approval needed</Badge>}</div><h2>{r.title}</h2><p>{r.summary}</p><small>{agents.find(a=>a.id===r.agentId)?.name} · {new Date(r.createdAt).toLocaleString()}</small></div><span>Open detail ↓</span></summary>{r.contextUsed&&<div className="context-used"><div><span className="eyebrow">PROFILE CONTEXT USED</span><b>{r.contextUsed.businessName}</b></div><dl><div><dt>Stage</dt><dd>{r.contextUsed.stage}</dd></div><div><dt>Industry</dt><dd>{r.contextUsed.industry}</dd></div><div><dt>Current goal</dt><dd>{r.contextUsed.currentGoal}</dd></div><div><dt>Budget</dt><dd>{r.contextUsed.budgetLevel}</dd></div></dl><small>Local profile memory influenced this mock output. No cloud sync or external lookup.</small></div>}<div className="report-context"><div><b>Risk / confidence</b><p>{r.riskNote||'This legacy local report was generated before structured risk notes were added.'}</p></div><div><b>Future integration</b><p>{r.futureIntegrationNote||'No external action was taken. Future connections remain disabled.'}</p></div></div><pre>{r.fullOutput}</pre><div className="report-actions"><button onClick={()=>copy(r.summary)}>Copy summary</button><button onClick={()=>copy(r.fullOutput)}>Copy full output</button><span>Was this useful?</span><button className={r.usefulnessRating==='useful'?'selected':''} onClick={()=>rate(r.id,'useful')}>Useful</button><button className={r.usefulnessRating==='not-useful'?'selected':''} onClick={()=>rate(r.id,'not-useful')}>Not useful</button></div></details>)}</div>:<div className="empty-with-action"><EmptyState title={reports.length?'No reports match these filters':'No reports yet'} text={reports.length?'Try clearing search or choosing another agent/tag.':'Run a recommended workflow to create a personalised local report.'}/>{!reports.length&&<button onClick={onRunRecommended}>View recommended workflows →</button>}</div>}
 </div>
}
