import type { AgentOutput } from '../types'
import { agents } from '../data/agents'
import { Badge } from '../components/Badge'
import { EmptyState } from '../components/EmptyState'

export function ReportsPage({ reports, rate, highlightedReportId }:{reports:AgentOutput[];rate:(id:string,r:AgentOutput['usefulnessRating'])=>void;highlightedReportId?:string}) {
 const copy=(text:string)=>navigator.clipboard?.writeText(text)
 return <div className="page"><header className="topbar"><div><p className="eyebrow">LOCAL KNOWLEDGE</p><h1>Outputs & reports</h1><p>Workflow, command, agent, blueprint, audit, and skill-gap work saved locally.</p></div><Badge>{reports.length} reports</Badge></header>{reports.length?<div className="reports-list">{reports.map(r=><details className={`report-card ${r.id===highlightedReportId?'highlighted':''}`} key={r.id}><summary><div><div className="meta-row"><Badge tone="live">{r.source||'workflow'}</Badge>{r.tags.map((t,i)=><Badge key={`${t}-${i}`}>{t}</Badge>)}{r.permissionLevel!==undefined&&<Badge>Level {r.permissionLevel}</Badge>}{r.estimatedCostMode&&<Badge>{r.estimatedCostMode} future mode</Badge>}{r.skillStatus&&<Badge tone="warning">{r.skillStatus.replace('_',' ')}</Badge>}{r.approvalNeeded&&<Badge tone="warning">Approval needed</Badge>}</div><h2>{r.title}</h2><p>{r.summary}</p><small>{agents.find(a=>a.id===r.agentId)?.name} · {new Date(r.createdAt).toLocaleString()}</small></div><span>View report ↓</span></summary><div className="report-context"><div><b>Risk / confidence</b><p>{r.riskNote||'This legacy local report was generated before structured risk notes were added.'}</p></div><div><b>Future integration</b><p>{r.futureIntegrationNote||'No external action was taken. Future connections remain disabled.'}</p></div></div><pre>{r.fullOutput}</pre><div className="report-actions"><button onClick={()=>copy(r.fullOutput)}>Copy output</button><span>Was this useful?</span><button className={r.usefulnessRating==='useful'?'selected':''} onClick={()=>rate(r.id,'useful')}>Yes</button><button className={r.usefulnessRating==='not-useful'?'selected':''} onClick={()=>rate(r.id,'not-useful')}>Not yet</button></div></details>)}</div>:<EmptyState title="No reports yet" text="Ask where to start building, run a workflow, or talk to an agent. Nothing will be sent or changed externally."/>}</div>
}
