import { useMemo, useState } from 'react'
import type { AgentOutput, Approval, ProjectActionItem, ProjectMilestone } from '../types'
import { agents } from '../data/agents'
import { Badge } from '../components/Badge'
import { EmptyState } from '../components/EmptyState'
import { BuilderPlanDetail } from '../components/BuilderPlanDetail'
import { loadProjectMilestones } from '../services/projectActionBoardService'
import { isRecordArray, loadLocal } from '../services/storage'

interface Props{reports:AgentOutput[];projectActions:ProjectActionItem[];projectMilestones?:ProjectMilestone[];approvals?:Approval[];rate:(id:string,r:AgentOutput['usefulnessRating'])=>void;highlightedReportId?:string;onRunRecommended:()=>void}
export function ReportsPage({reports,projectActions,projectMilestones=[],approvals=[],rate,highlightedReportId,onRunRecommended}:Props){
 const [search,setSearch]=useState('');const [agentFilter,setAgentFilter]=useState('all');const [tagFilter,setTagFilter]=useState('all');const [openId,setOpenId]=useState<string|undefined>(()=>{if(highlightedReportId)return highlightedReportId;try{const id=sessionStorage.getItem('operator.openPlan')||undefined;sessionStorage.removeItem('operator.openPlan');return id}catch{return undefined}});const [copied,setCopied]=useState('')
 const agentIds=useMemo(()=>[...new Set(reports.map(report=>report.agentId))],[reports]);const tags=useMemo(()=>[...new Set(reports.flatMap(report=>report.tags||[]))].sort(),[reports])
 const effectiveMilestones=projectMilestones.length?projectMilestones:loadProjectMilestones();const effectiveApprovals=approvals.length?approvals:loadLocal('operator.approvals',[],isRecordArray<Approval>)
 const filtered=reports.filter(report=>(agentFilter==='all'||report.agentId===agentFilter)&&(tagFilter==='all'||(report.tags||[]).includes(tagFilter))&&(!search.trim()||`${report.title} ${report.summary} ${report.fullOutput} ${(report.tags||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase())))
 const selected=reports.find(report=>report.id===openId);const copy=(id:string,text:string)=>{void navigator.clipboard?.writeText(text);setCopied(id);setTimeout(()=>setCopied(''),2200)}
 return <div className="page"><header className="topbar friendly-topbar"><div><p className="eyebrow">YOUR WORK</p><h1>Saved Work</h1><p>Useful results from your AI team, ready to review and copy.</p></div><Badge>{reports.length} saved</Badge></header>
  {selected&&(selected.source==='business-builder'||selected.tags?.includes('guided-builder'))?<BuilderPlanDetail report={selected} actions={projectActions} milestones={effectiveMilestones} approvals={effectiveApprovals} rate={rating=>rate(selected.id,rating)} close={()=>setOpenId(undefined)}/>:selected&&<section className="report-detail"><div className="report-detail-head"><div><div className="meta-row"><Badge tone="live">{agents.find(agent=>agent.id===selected.agentId)?.name||'AI teammate'}</Badge>{selected.sourceProjectTitle&&<Badge>Project: {selected.sourceProjectTitle}</Badge>}{selected.projectActionType&&<Badge>{selected.projectActionType.replaceAll('-',' ')}</Badge>}{selected.approvalNeeded&&<Badge tone="warning">Needs your review</Badge>}</div><h2>{selected.title}</h2><small>{new Date(selected.createdAt).toLocaleString()}</small></div><button aria-label="Close report" onClick={()=>setOpenId(undefined)}>×</button></div>
   <section><h3>Summary</h3><p>{selected.plainEnglishSummary||selected.summary}</p>{projectActions.some(item=>item.sourceOutputId===selected.id)&&<small>{projectActions.filter(item=>item.sourceOutputId===selected.id).length} actions added to Project Board.</small>}</section>
   <div className="report-detail-grid"><section><h3>What your teammate found</h3><ul>{(selected.keyFindings||[selected.summary]).map(item=><li key={item}>{item}</li>)}</ul></section><section><h3>What to do next</h3><ol>{(selected.recommendedNextSteps||['Review the full details and choose the most useful next action.']).map(item=><li key={item}>{item}</li>)}</ol></section></div>
   {selected.copyableText&&<section className="copy-box"><div><h3>Ready to copy and use</h3><button onClick={()=>copy(selected.id,selected.copyableText!)}>{copied===selected.id?'Copied — ready to paste.':'Copy'}</button></div><pre>{selected.copyableText}</pre></section>}
   {selected.approvalNeeded&&<section className="approval-explainer"><Badge tone="warning">Needs approval</Badge><div><h3>Why this is waiting for you</h3><p>{selected.approvalSummary||'This draft could affect an external tool in the future, so it has been placed in Approvals instead of being sent automatically.'}</p><small>{selected.riskNote||'Nothing external happened.'} The app will not send, publish, pay, reconcile, submit, or change anything automatically.</small></div></section>}
   <details className="full-details"><summary>View full details</summary><pre>{selected.fullOutput}</pre></details>
   <div className="helpful-review"><span>Was this helpful?</span><button className={selected.usefulnessRating==='useful'?'selected':''} onClick={()=>rate(selected.id,'useful')}>Useful</button><button className={selected.usefulnessRating==='not-useful'?'selected':''} onClick={()=>rate(selected.id,'not-useful')}>Not useful</button><small>Saved only in this browser.</small></div>
  </section>}
  <section className="report-filters"><label>Search saved work<input aria-label="Search reports" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search titles or topics"/></label><label>Helper<select aria-label="Filter by agent" value={agentFilter} onChange={event=>setAgentFilter(event.target.value)}><option value="all">All helpers</option>{agentIds.map(id=><option value={id} key={id}>{agents.find(agent=>agent.id===id)?.name||id}</option>)}</select></label><label>Topic<select aria-label="Filter by tag" value={tagFilter} onChange={event=>setTagFilter(event.target.value)}><option value="all">All topics</option>{tags.map(tag=><option value={tag} key={tag}>{tag}</option>)}</select></label><Badge tone={filtered.length?'live':'neutral'}>{filtered.length} shown</Badge></section>
  {filtered.length?<div className="reports-list friendly-reports">{filtered.map(report=><article className={`report-card ${report.id===highlightedReportId?'highlighted':''}`} key={report.id}><div className="report-card-top"><div className="meta-row"><Badge tone="live">{agents.find(agent=>agent.id===report.agentId)?.name||'AI teammate'}</Badge>{(report.tags||[]).slice(0,3).map(tag=><Badge key={tag}>{tag}</Badge>)}</div>{report.usefulnessRating&&<span className={`rating-status ${report.usefulnessRating}`}>{report.usefulnessRating==='useful'?'Marked useful':'Marked not useful'}</span>}</div><h2>{report.title}</h2><p>{report.plainEnglishSummary||report.summary}</p><small>{new Date(report.createdAt).toLocaleString()}</small><div className="report-card-actions"><button className="primary" onClick={()=>{setOpenId(report.id);scrollTo({top:0,behavior:'smooth'})}}>Open report</button>{report.copyableText&&<button onClick={()=>copy(`card-${report.id}`,report.copyableText!)}>{copied===`card-${report.id}`?'Copied — ready to paste.':'Copy output'}</button>}{report.approvalNeeded&&<Badge tone="warning">Needs review</Badge>}</div></article>)}</div>:<div className="empty-with-action"><EmptyState title={reports.length?'No saved work matches':'No saved work yet'} text={reports.length?'Try clearing the search or choosing another helper/topic.':'Run a recommended workflow to create your first useful report.'}/>{!reports.length&&<button onClick={onRunRecommended}>Choose a workflow →</button>}</div>}
 </div>
}
