import { useState } from 'react'
import type { BusinessProfile, FounderProfile } from '../types'
import { integrations } from '../data/integrations'
import { aiCostGuardrails } from '../data/guardrails'
import { Badge } from '../components/Badge'
import { PermissionGuide } from '../components/PermissionGuide'
import { BusinessProfileForm } from '../components/BusinessProfileForm'
import { FounderProfileForm } from '../components/FounderProfileForm'
import { getSelectedProviderId, providers, saveSelectedProviderId } from '../services/ai/providers'
import { toolRegistry } from '../services/tools/toolRegistry'
import { getExecutionResults, getToolExecutionLogs } from '../services/execution/executionLogsStorage'

export function SettingsPage({profile,founderProfile,onSaveProfile,onSaveFounderProfile,onResetProfile}:{profile:BusinessProfile;founderProfile:FounderProfile;onSaveProfile:(profile:BusinessProfile)=>void;onSaveFounderProfile:(profile:FounderProfile)=>void;onResetProfile:()=>void}) {
 const [exportText,setExportText]=useState('')
 const [selectedProvider,setSelectedProvider]=useState(()=>getSelectedProviderId())
 const readable=`${profile.businessName}\nFounder: ${profile.founderName}\nStage: ${profile.stage}\nIndustry: ${profile.industry}\nProduct/service: ${profile.productOrService}\nTarget customer: ${profile.targetCustomer}\nCurrent goal: ${profile.currentGoal}\nBiggest challenge: ${profile.biggestChallenge}\nBudget: ${profile.budgetLevel}\nTone: ${profile.preferredTone}\nRisk comfort: ${profile.riskComfort}\nDesired integrations: ${profile.desiredIntegrations.join(', ')||'None selected'}`
 const exportJson=()=>{const blob=new Blob([JSON.stringify(profile,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${profile.businessName.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'business'}-profile.json`;anchor.click();URL.revokeObjectURL(url)}
 return <div className="page"><header className="topbar friendly-topbar"><div><p className="eyebrow">MAKE IT YOURS</p><h1>Settings</h1><p>Update your details and choose how your AI team should communicate.</p></div></header><div className="demo-mode-notice"><b>Local demo mode</b><span>Your information stays in this browser. No cloud sync, real AI connection, or external action.</span></div>
  <section className="panel profile-settings"><div className="section-title"><div><span className="eyebrow">PERSONALISED OPERATOR LAYER</span><h2>Founder Profile</h2></div><Badge tone="live">Local recommendation context</Badge></div><p className="muted">Projects, priorities, tone, risk preference, and default permission influence recommendations and mock outputs. Workflow safety rules always win.</p><FounderProfileForm key={founderProfile.updatedAt} initial={founderProfile} onSave={onSaveFounderProfile}/></section>
  <section className="panel profile-settings"><div className="section-title"><div><span className="eyebrow">LOCAL BUSINESS MEMORY · LEVEL 0</span><h2>Business Profile</h2></div><Badge tone="live">Saved in this browser</Badge></div><div className="memory-notice"><b>Local-only memory. No cloud sync and no secrets.</b><span>Edit or delete this profile whenever you like. Future Supabase storage must use authentication, RLS, and server-side controls.</span></div><BusinessProfileForm key={profile.updatedAt} initial={profile} onSave={onSaveProfile}/><div className="profile-export"><button onClick={exportJson}>Export JSON</button><button onClick={()=>setExportText(readable)}>Preview readable text</button><button className="danger" onClick={()=>{if(confirm('Clear this local business profile and return to onboarding? Reports and approvals will remain.'))onResetProfile()}}>Clear profile & restart onboarding</button></div>{exportText&&<div className="export-preview"><div><b>Readable profile export</b><button onClick={()=>navigator.clipboard?.writeText(exportText)}>Copy text</button></div><pre>{exportText}</pre></div>}</section>
  <div className="settings-grid"><section className="panel form-panel"><h2>Workspace</h2><label>Preferred tone<input value={profile.preferredTone} disabled/></label><label>Main business<input value={`${profile.businessName} · ${profile.stage}`} disabled/></label><p className="settings-note">Edit these values in Business Profile above so every local response uses one source of truth.</p></section><section className="panel form-panel"><h2>Model provider <Badge>Placeholder</Badge></h2><label>API provider<select disabled><option>OpenAI-compatible (future)</option></select></label><label>API key placeholder<input type="password" placeholder="Not stored or connected" disabled /></label><div className="warning-box"><b>Do not paste a real key.</b><p>This is UI-only. Production keys must live in backend secrets or environment variables—never localStorage or client bundles.</p></div></section></div>
  <section><div className="section-title"><div><span className="eyebrow">BACKEND-READY · MOCK-ONLY</span><h2>AI Providers & Execution</h2></div><Badge tone="live">{getExecutionResults().length} local runs · {getToolExecutionLogs().length} tool logs</Badge></div><div className="provider-selector"><label>Selected provider<select value={selectedProvider} onChange={e=>{const value=saveSelectedProviderId(e.target.value);setSelectedProvider(value)}}>{providers.map(provider=><option key={provider.id} value={provider.id} disabled={!provider.enabled}>{provider.name}{provider.enabled?'':' · disabled'}</option>)}</select></label><div className="warning-box"><b>Mock Local Provider is the only executable provider.</b><p>Real provider keys must later live in backend environment variables—not frontend code or localStorage.</p></div></div><div className="provider-grid">{providers.map(provider=><article key={provider.id}><div><h3>{provider.name}</h3><p>{provider.description}</p></div><div className="meta-row"><Badge tone={provider.enabled?'live':'neutral'}>{provider.status}</Badge><Badge>{provider.type}</Badge><Badge>{provider.isMock?'mock':'future'}</Badge></div><small>{provider.capabilities.join(' · ')} · Auth: {provider.authType}</small></article>)}</div></section>
  <section><div className="section-title"><div><span className="eyebrow">CAPABILITY REGISTRY</span><h2>Tool Registry</h2></div><Badge>{toolRegistry.filter(tool=>tool.enabled).length} enabled mock · {toolRegistry.filter(tool=>!tool.enabled).length} future</Badge></div><div className="tool-registry">{toolRegistry.map(tool=><article key={tool.id}><div><h3>{tool.id}</h3><p>{tool.description}</p></div><div className="meta-row"><Badge tone={tool.enabled?'live':'neutral'}>{tool.enabled?'enabled':'disabled'}</Badge><Badge>Level {tool.permissionLevel}</Badge><Badge tone={tool.riskLevel}>{tool.riskLevel}</Badge>{tool.requiresApproval&&<Badge tone="warning">approval</Badge>}</div><small>{tool.inputSchemaDescription} → {tool.outputSchemaDescription}<br/>Future: {tool.futureIntegration}</small></article>)}</div></section>
  <section><div className="section-title"><div><span className="eyebrow">LOCAL PLACEHOLDERS</span><h2>AI Cost & Autonomy Guardrails</h2></div><Badge tone="live">0 real tokens</Badge></div><div className="guardrail-settings"><div className="panel form-panel guardrail-controls"><label>Monthly AI budget limit<input defaultValue="£25 placeholder" disabled/></label><label>Default future AI mode<select defaultValue="cheap" disabled><option value="cheap">Cheap</option><option>Standard</option><option>Premium</option></select></label><label className="check-row"><input type="checkbox" defaultChecked disabled/> Require approval before premium mode</label><label className="check-row"><input type="checkbox" defaultChecked disabled/> Require approval before external agent execution</label><label className="check-row"><input type="checkbox" defaultChecked disabled/> Disable background autonomous runs</label><label className="check-row"><input type="checkbox" defaultChecked disabled/> Allow self-audit suggestions only</label><label className="check-row"><input type="checkbox" defaultChecked disabled/> Require review before platform-wide skills</label><label className="check-row"><input type="checkbox" defaultChecked disabled/> Block production and irreversible changes</label></div><div className="guardrail-list">{aiCostGuardrails.map(g=><article key={g.id}><span className="guardrail-dot">✓</span><div><b>{g.name}</b><p>{g.description}</p></div><Badge tone={g.actionWhenLimitReached==='block'?'restricted':'warning'}>{g.actionWhenLimitReached.replace('-',' ')}</Badge></article>)}</div></div><p className="settings-note">These controls are local placeholders only. They are not connected to billing, model selection, APIs, background jobs, or external agents.</p></section>
  <section><div className="section-title"><div><span className="eyebrow">FUTURE CONNECTIONS</span><h2>Integrations</h2></div><Badge>All disconnected</Badge></div><div className="integration-grid">{integrations.map(x=><article key={x.id}><span className="integration-icon">{x.name[0]}</span><div><h3>{x.name}</h3><p>{x.description}</p></div><Badge>Placeholder</Badge></article>)}</div></section><section><div className="section-title"><div><span className="eyebrow">SAFETY MODEL</span><h2>Permission levels</h2></div></div><PermissionGuide/></section></div>
}
