import { useMemo, useState } from 'react'
import type { AgentOutput, Approval, ProjectHelpActionType, ProjectHelpBundle, ProjectPriority, ProjectStage, ProjectStatus, ProjectType, ProjectWorkspaceProject } from '../types'
import { Badge } from '../components/Badge'
import { EmptyState } from '../components/EmptyState'
import { projectPriorities, projectStages, projectStatuses, projectTypes } from '../services/projectWorkspaceService'
import { projectHelpActions, routeProjectHelpRequest } from '../services/projectAiHelpService'
import { agents } from '../data/agents'

interface Props { projects:ProjectWorkspaceProject[]; reports:AgentOutput[]; approvals:Approval[]; saveProject:(project:ProjectWorkspaceProject)=>void; runProjectHelp:(project:ProjectWorkspaceProject,action:ProjectHelpActionType)=>ProjectHelpBundle; go:(page:'agents'|'reports'|'approvals')=>void }
const blank = (): ProjectWorkspaceProject => { const now=new Date().toISOString(); return {id:crypto.randomUUID(),name:'',type:'Business idea',description:'',status:'Draft',stage:'Idea',priority:'Medium',ownerGoal:'',createdAt:now,updatedAt:now,linkedOutputIds:[],linkedApprovalIds:[],notes:[],nextActions:[]} }

export function WorkspacePage({projects,reports,approvals,saveProject,runProjectHelp,go}:Props){
 const [selectedId,setSelectedId]=useState(projects[0]?.id||''); const [draft,setDraft]=useState<ProjectWorkspaceProject|null>(null); const [note,setNote]=useState(''); const [action,setAction]=useState('')
 const [helpResult,setHelpResult]=useState<ProjectHelpBundle|null>(null);const [selectedHelp,setSelectedHelp]=useState<ProjectHelpActionType|null>(null);const [copied,setCopied]=useState(false)
 const selected=projects.find(p=>p.id===selectedId)||projects[0]; const active=projects.filter(p=>!['Complete','Paused'].includes(p.status)); const needs=projects.filter(p=>p.status==='Needs review'||p.status==='Waiting for approval')
 const linkedReports=useMemo(()=>reports.filter(r=>selected?.linkedOutputIds.includes(r.id)||r.projectId===selected?.id),[reports,selected]); const linkedApprovals=useMemo(()=>approvals.filter(a=>selected?.linkedApprovalIds.includes(a.id)||selected?.linkedOutputIds.includes(a.sourceOutputId||'')||a.projectId===selected?.id),[approvals,selected])
 const open=(project:ProjectWorkspaceProject)=>{setSelectedId(project.id);setDraft(null);setNote('');setAction('');setHelpResult(null);setSelectedHelp(null);scrollTo({top:0,behavior:'smooth'})}
 const startEdit=(project:ProjectWorkspaceProject)=>setDraft({...project,linkedOutputIds:[...project.linkedOutputIds],linkedApprovalIds:[...project.linkedApprovalIds],notes:[...project.notes],nextActions:[...project.nextActions]})
 const startNew=()=>{const next=blank();setSelectedId(next.id);setDraft(next);setNote('');setAction('')}
 const current=draft||selected
 const persist=(project:ProjectWorkspaceProject)=>{const saved={...project,updatedAt:new Date().toISOString()};saveProject(saved);setDraft(saved);setSelectedId(saved.id)}
 const updateDraft=<K extends keyof ProjectWorkspaceProject>(key:K,value:ProjectWorkspaceProject[K])=>setDraft(prev=>({...(prev||current||blank()),[key]:value,updatedAt:new Date().toISOString()}))
 const addNote=()=>{if(!current||!note.trim())return;persist({...current,notes:[{id:crypto.randomUUID(),text:note.trim(),createdAt:new Date().toISOString()},...current.notes]});setNote('')}
 const addAction=()=>{if(!current||!action.trim())return;persist({...current,nextActions:[...current.nextActions,{id:crypto.randomUUID(),text:action.trim(),done:false,createdAt:new Date().toISOString()}]});setAction('')}
 const toggleAction=(id:string)=>{if(!current)return;persist({...current,nextActions:current.nextActions.map(item=>item.id===id?{...item,done:!item.done,completedAt:!item.done?new Date().toISOString():undefined}:item)})}
 const toggleReport=(id:string)=>{if(!current)return;const has=current.linkedOutputIds.includes(id);persist({...current,linkedOutputIds:has?current.linkedOutputIds.filter(x=>x!==id):[id,...current.linkedOutputIds]})}
 const askTeam=(help:ProjectHelpActionType)=>{if(!current||draft)return;setSelectedHelp(help);setHelpResult(runProjectHelp(current,help));setCopied(false)}
 const copyResult=()=>{if(!helpResult?.output.copyableText)return;void navigator.clipboard?.writeText(helpResult.output.copyableText);setCopied(true);setTimeout(()=>setCopied(false),2200)}
 return <div className="page workspace-page"><header className="topbar friendly-topbar"><div><p className="eyebrow">PROJECT WORKSPACE</p><h1>Your business command center</h1><p>Keep ideas, plans, saved work, notes, and next steps together.</p></div><button className="workspace-new" onClick={startNew}>New project</button></header>
  <section className="workspace-boundary"><b>Your projects only.</b><span>This workspace is for your own business projects and outputs. It does not change the AI Company Operator platform itself.</span></section>
  <div className="workspace-stats"><article><b>{active.length}</b><span>Active projects</span></article><article><b>{projects.flatMap(p=>p.nextActions).filter(a=>!a.done).length}</b><span>Next steps</span></article><article><b>{needs.length}</b><span>Need review or approval</span></article></div>
  {current&&<section className="project-detail"><div className="project-detail-head"><div><Badge tone={current.status==='Waiting for approval'?'warning':'live'}>{current.status}</Badge><h2>{draft?.id===current.id?(current.name||'New project'):current.name}</h2><p>{current.type} · {current.stage} · {current.priority} priority</p></div>{!draft&&<button onClick={()=>startEdit(current)}>Edit</button>}</div>
   {draft?<div className="project-form"><label>What are you building?<input value={draft.name} onChange={e=>updateDraft('name',e.target.value)} placeholder="e.g. Website for my bakery"/></label><label>Project type<select value={draft.type} onChange={e=>updateDraft('type',e.target.value as ProjectType)}>{projectTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>What stage is it in?<select value={draft.stage} onChange={e=>updateDraft('stage',e.target.value as ProjectStage)}>{projectStages.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={draft.status} onChange={e=>updateDraft('status',e.target.value as ProjectStatus)}>{projectStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={draft.priority} onChange={e=>updateDraft('priority',e.target.value as ProjectPriority)}>{projectPriorities.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Owner goal<input value={draft.ownerGoal} onChange={e=>updateDraft('ownerGoal',e.target.value)} placeholder="e.g. Launch a simple page this month"/></label><label className="wide">Short description<textarea value={draft.description} onChange={e=>updateDraft('description',e.target.value)} placeholder="Explain the project in plain English"/></label><div className="project-form-actions"><button onClick={()=>setDraft(null)}>Close</button><button className="primary" disabled={!draft.name.trim()} onClick={()=>persist(draft)}>Save project</button></div></div>:<p className="project-description">{current.description||'No description yet. Add a short note about what you are building.'}</p>}
   <div className="project-sections"><section><h3>Next steps</h3><div className="add-row"><input value={action} onChange={e=>setAction(e.target.value)} placeholder="Add a simple next step"/><button onClick={addAction}>Add</button></div>{current.nextActions.length?current.nextActions.map(item=><label className="next-step" key={item.id}><input type="checkbox" checked={item.done} onChange={()=>toggleAction(item.id)}/><span className={item.done?'done':''}>{item.text}</span></label>):<p className="friendly-empty">No next steps yet. Add one small action to keep moving.</p>}</section><section><h3>Notes</h3><div className="add-row"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a quick note"/><button onClick={addNote}>Add</button></div>{current.notes.length?current.notes.map(item=><p className="project-note" key={item.id}>{item.text}<small>{new Date(item.createdAt).toLocaleString()}</small></p>):<p className="friendly-empty">No notes yet.</p>}</section></div>
   <div className="project-sections"><section><h3>Related reports</h3>{reports.length?<div className="link-list">{reports.slice(0,6).map(report=><label key={report.id}><input type="checkbox" checked={current.linkedOutputIds.includes(report.id)} onChange={()=>toggleReport(report.id)}/><span>{report.title}</span></label>)}</div>:<p className="friendly-empty">Run a workflow to save work, then link it here.</p>}{linkedReports.length>0&&<button className="text-button" onClick={()=>go('reports')}>Open Saved Work</button>}</section><section><h3>Needs approval</h3>{linkedApprovals.length?linkedApprovals.map(item=><button className="approval-link" key={item.id} onClick={()=>go('approvals')}><b>{item.title}</b><small>{item.status} · {item.riskLevel} risk</small></button>):<p className="friendly-empty">Project-related approvals will appear here when linked through saved work.</p>}</section></div>
   {!draft&&<section className="project-ai-help"><div className="project-ai-heading"><div><span className="eyebrow">ASK THE AI TEAM</span><h3>What do you want help with?</h3><p>Choose one simple action. Your AI teammate will prepare a local report and save it to this project.</p></div><Badge tone="live">Local only</Badge></div><div className="project-help-actions">{projectHelpActions.map(item=>{const agentId=routeProjectHelpRequest(current,item.id);return <button className={selectedHelp===item.id?'selected':''} key={item.id} onClick={()=>askTeam(item.id)}><span>↗</span><div><b>{item.label}</b><small>{agents.find(agent=>agent.id===agentId)?.name}</small></div></button>})}</div><p className="project-help-safety">Nothing is sent or changed. Payments, reconciliation, tax submissions, production deletion, commitments, and irreversible actions are blocked.</p></section>}
   {helpResult&&<section className="project-ai-result"><div className="project-ai-result-head"><span className="result-check">✓</span><div><span className="eyebrow">AI TEAM SUGGESTION</span><h3>{helpResult.output.title}</h3><p>{agents.find(agent=>agent.id===helpResult.output.agentId)?.name} · Saved to this project</p></div></div><p>{helpResult.output.plainEnglishSummary||helpResult.output.summary}</p><div className="project-result-columns"><section><b>What the team found</b><ul>{helpResult.output.keyFindings?.slice(0,4).map(item=><li key={item}>{item}</li>)}</ul></section><section><b>What to do next</b><ol>{helpResult.output.recommendedNextSteps?.map(item=><li key={item}>{item}</li>)}</ol></section></div>{helpResult.approval&&<div className="project-approval-notice"><Badge tone="warning">Needs approval before action</Badge><p>{helpResult.output.approvalSummary}</p><button onClick={()=>go('approvals')}>Open approval</button></div>}<div className="project-result-actions"><button onClick={copyResult}>{copied?'Copied — ready to paste.':'Copy useful output'}</button><button className="primary" onClick={()=>go('reports')}>Open saved report</button></div></section>}
  </section>}
  <section><div className="simple-section-title"><h2>Your projects</h2><button onClick={startNew}>Create</button></div>{projects.length?<div className="project-grid">{projects.map(project=><button className={project.id===current?.id?'active':''} key={project.id} onClick={()=>open(project)}><div><Badge tone={project.status==='Waiting for approval'?'warning':'neutral'}>{project.status}</Badge><Badge>{project.stage}</Badge></div><b>{project.name}</b><span>{project.description||project.ownerGoal||'No description yet'}</span><small>{project.nextActions.filter(a=>!a.done).length} next steps · {project.linkedOutputIds.length} reports</small></button>)}</div>:<EmptyState title="No projects yet" text="Create a local project for a business idea, website, app, launch plan, campaign, research, or admin work. Everything stays in this browser."/>}</section>
 </div>
}
