import { useState } from 'react'
import type { AgentOutput, Approval, BuilderPlanData, ProjectActionItem, ProjectMilestone } from '../types'
import { Badge } from './Badge'

function legacyPlan(report:AgentOutput):BuilderPlanData{
 const inputLines=(report.keyFindings||[]).filter(item=>item.includes(':')&&!item.startsWith('Best fit:')&&!item.startsWith('Project context:')).map(item=>{const index=item.indexOf(':');return {label:item.slice(0,index),value:item.slice(index+1).trim()}})
 const type=(report.tags||[]).find(tag=>['website','offer','launch','ads','app','automation'].includes(tag))||'business plan'
 return {builderWorkflowId:report.projectActionType?.replace('builder:','')||'older-builder-plan',builderType:type,basedOn:inputLines.length?inputLines:[{label:'Project',value:report.sourceProjectTitle||'User-owned project'},{label:'Context',value:'This older plan did not store individual form answers.'}],sections:[{title:'Recommended plan',content:report.fullOutput||report.summary}],suggestedMilestones:[],approvalFutureActions:report.approvalNeeded?['Review the related simulated approval preview before any future external action.']:[],safetyNote:'Planning only · this is an older local builder report. No real action was taken.'}
}

export function BuilderPlanDetail({report,actions,milestones,approvals,rate,close}:{report:AgentOutput;actions:ProjectActionItem[];milestones:ProjectMilestone[];approvals:Approval[];rate:(rating:AgentOutput['usefulnessRating'])=>void;close:()=>void}){
 const [copied,setCopied]=useState('');const plan=report.builderPlan||legacyPlan(report);const relatedActions=actions.filter(item=>item.sourceOutputId===report.id);const relatedMilestones=milestones.filter(item=>item.projectId===report.projectId&&(!report.builderPlan||plan.suggestedMilestones.includes(item.title)));const relatedApprovals=approvals.filter(item=>item.sourceOutputId===report.id);const milestoneRows=relatedMilestones.length?relatedMilestones.map(item=>({id:item.id,title:item.title})):plan.suggestedMilestones.map((title,index)=>({id:`suggested-${index}`,title}))
 const copy=async(key:string,text:string)=>{try{await navigator.clipboard?.writeText(text);setCopied(key);setTimeout(()=>setCopied(''),1800)}catch{setCopied('')}}
 const nextText=(report.recommendedNextSteps||relatedActions.map(item=>item.title)).map((item,index)=>`${index+1}. ${item}`).join('\n');const fullText=report.copyableText||report.fullOutput
 return <section className="builder-plan-detail"><header><div><div className="meta-row"><Badge tone="live">Planning only</Badge><Badge>{plan.builderType.replaceAll('-',' ')}</Badge>{report.sourceProjectTitle&&<Badge>Project: {report.sourceProjectTitle}</Badge>}</div><h2>{report.title}</h2><p>{new Date(report.createdAt).toLocaleString()}</p></div><button aria-label="Close plan" onClick={close}>×</button></header>
  <div className="plan-safety"><b>No real action taken</b><span>Nothing was published, deployed, sent, or spent. Approval is required before any sensitive future action.</span>{plan.builderType==='ads'&&<strong>No ad was launched. No money was spent. This is a campaign plan only.</strong>}</div>
  <section className="plan-based-on"><div><span className="eyebrow">BASED ON</span><h3>Inputs used</h3></div><dl>{plan.basedOn.map(item=><div key={`${item.label}-${item.value}`}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl></section>
  <section className="plan-summary"><span className="eyebrow">SUMMARY</span><h3>What was created</h3><p>{report.plainEnglishSummary||report.summary}</p><button onClick={()=>copy('summary',report.plainEnglishSummary||report.summary)}>{copied==='summary'?'Summary copied':'Copy summary'}</button></section>
  <section className="plan-sections"><span className="eyebrow">RECOMMENDED PLAN</span>{plan.sections.map((section,index)=><article key={`${section.title}-${index}`}><h3>{section.title}</h3><p>{section.content}</p><button onClick={()=>copy(`section-${index}`,`${section.title}\n\n${section.content}`)}>{copied===`section-${index}`?'Copied':`Copy ${section.title.toLowerCase()}`}</button></article>)}</section>
  <div className="plan-follow-up"><section><h3>Next actions</h3>{(report.recommendedNextSteps||relatedActions.map(item=>item.title)).map((item,index)=><p key={`${item}-${index}`}>✓ {item}</p>)}<button onClick={()=>copy('actions',nextText)}>{copied==='actions'?'Actions copied':'Copy next actions'}</button></section><section><h3>Milestones</h3>{milestoneRows.map(item=><p key={item.id}>◇ {item.title}</p>)}{!milestoneRows.length&&<p>Older plan · milestones were not stored with this report.</p>}</section></div>
  <section className="plan-approvals"><h3>Things that need approval</h3>{relatedApprovals.length?relatedApprovals.map(item=><article key={item.id}><Badge tone="warning">{item.status}</Badge><b>{item.title}</b><p>{item.reason}</p></article>):plan.approvalFutureActions.length?plan.approvalFutureActions.map(item=><p key={item}>! {item}</p>):<p>No approval is needed for this planning output.</p>}<small>{plan.safetyNote}</small></section>
  <div className="plan-copy-bar"><button onClick={()=>copy('full',fullText)}>{copied==='full'?'Full plan copied':'Copy full plan'}</button><span>Was this useful?</span><button className={report.usefulnessRating==='useful'?'selected':''} onClick={()=>rate('useful')}>Useful</button><button className={report.usefulnessRating==='not-useful'?'selected':''} onClick={()=>rate('not-useful')}>Not useful</button></div>
 </section>
}
