import { useState } from 'react'
import type { BusinessProfile } from '../types'

export const emptyProfile = (): BusinessProfile => { const now=new Date().toISOString(); return {id:crypto.randomUUID(),founderName:'',businessName:'',stage:'idea',industry:'',productOrService:'',targetCustomer:'',currentGoal:'',biggestChallenge:'',budgetLevel:'lean',preferredTone:'direct',riskComfort:'cautious',desiredIntegrations:[],createdAt:now,updatedAt:now} }
const integrations=['GitHub','Gmail','Google Calendar','Xero','Supabase','Slack','Webhooks','MCP servers','Excel export']

export function BusinessProfileForm({ initial, onSave, submitLabel='Save business profile' }:{initial:BusinessProfile;onSave:(profile:BusinessProfile)=>void;submitLabel?:string}) {
 const [profile,setProfile]=useState(initial)
 const set=(key:keyof BusinessProfile,value:string|string[])=>setProfile(current=>({...current,[key]:value,updatedAt:new Date().toISOString()}))
 const toggle=(value:string)=>set('desiredIntegrations',profile.desiredIntegrations.includes(value)?profile.desiredIntegrations.filter(item=>item!==value):[...profile.desiredIntegrations,value])
 return <form className="profile-form" onSubmit={event=>{event.preventDefault();onSave(profile)}}>
  <div className="profile-grid"><label>Founder name<input required value={profile.founderName} onChange={e=>set('founderName',e.target.value)} placeholder="Your name"/><small>Used for greetings and founder context.</small></label><label>Business name<input required value={profile.businessName} onChange={e=>set('businessName',e.target.value)} placeholder="Your business or working title"/></label>
  <label>Business stage<select value={profile.stage} onChange={e=>set('stage',e.target.value)}><option value="idea">Idea</option><option value="validating">Validating</option><option value="pre-launch">Pre-launch</option><option value="launched">Launched</option><option value="growing">Growing</option><option value="established">Established</option></select></label><label>Industry<input required value={profile.industry} onChange={e=>set('industry',e.target.value)} placeholder="e.g. Mobile services, retail, SaaS"/></label>
  <label className="wide">Main product or service<textarea required value={profile.productOrService} onChange={e=>set('productOrService',e.target.value)} placeholder="What will the business provide?"/></label><label className="wide">Target customer<textarea required value={profile.targetCustomer} onChange={e=>set('targetCustomer',e.target.value)} placeholder="Who has the problem you solve?"/></label>
  <label className="wide">Current goal<textarea required value={profile.currentGoal} onChange={e=>set('currentGoal',e.target.value)} placeholder="What outcome matters most right now?"/></label><label className="wide">Biggest challenge<textarea required value={profile.biggestChallenge} onChange={e=>set('biggestChallenge',e.target.value)} placeholder="What is making progress difficult?"/></label>
  <label>Budget level<select value={profile.budgetLevel} onChange={e=>set('budgetLevel',e.target.value)}><option value="no-budget">No starting budget</option><option value="lean">Lean / under £1k</option><option value="modest">Modest / £1k–£10k</option><option value="funded">Funded / over £10k</option></select></label><label>Preferred tone<select value={profile.preferredTone} onChange={e=>set('preferredTone',e.target.value)}><option value="direct">Direct and thoughtful</option><option value="concise">Concise</option><option value="warm">Warm and encouraging</option><option value="formal">Formal</option></select></label><label>Risk comfort<select value={profile.riskComfort} onChange={e=>set('riskComfort',e.target.value)}><option value="cautious">Cautious</option><option value="balanced">Balanced</option><option value="experimental">Experimental, with guardrails</option></select></label></div>
  <fieldset><legend>Desired future integrations</legend><p>Select interests only. Nothing will be connected in this MVP.</p><div className="integration-checks">{integrations.map(item=><label key={item}><input type="checkbox" checked={profile.desiredIntegrations.includes(item)} onChange={()=>toggle(item)}/>{item}</label>)}</div></fieldset>
  <button className="profile-submit" type="submit">{submitLabel} →</button>
 </form>
}
