import { useState } from 'react'
import type { BuilderRunBundle, ProjectWorkspaceProject } from '../types'
import { builderWorkflows } from '../services/operator.builderWorkflows'
import { Badge } from './Badge'

type Step='choose'|'answer'|'review'|'result'
export function GuidedBuilder({project,run,openReports,openApprovals,openActions=()=>document.querySelector('.action-board')?.scrollIntoView({behavior:'smooth'})}:{project:ProjectWorkspaceProject;run:(workflowId:string,inputs:Record<string,string>)=>BuilderRunBundle;openReports:()=>void;openApprovals:()=>void;openActions?:()=>void}){
 const [selectedId,setSelectedId]=useState(builderWorkflows[0].id);const [inputs,setInputs]=useState<Record<string,string>>({});const [result,setResult]=useState<BuilderRunBundle|null>(null);const [step,setStep]=useState<Step>('choose');const [copied,setCopied]=useState<'summary'|'full'|null>(null)
 const selected=builderWorkflows.find(item=>item.id===selectedId)||builderWorkflows[0]
 const usedInputs=Object.fromEntries(selected.inputPrompts.map(item=>[item.id,inputs[item.id]?.trim()||item.defaultValue]))
 const choose=(id:string)=>{setSelectedId(id);setInputs({});setResult(null);setStep('answer')}
 const useDefaults=()=>setInputs(Object.fromEntries(selected.inputPrompts.map(item=>[item.id,item.defaultValue])))
 const build=()=>{setResult(run(selected.id,usedInputs));setStep('result')}
 const copy=async(kind:'summary'|'full')=>{if(!result)return;const text=kind==='summary'?`${result.output.title}\n\n${result.output.summary}\n\n${result.output.recommendedNextSteps?.map((item,index)=>`${index+1}. ${item}`).join('\n')||''}`:result.output.copyableText||result.output.fullOutput;try{await navigator.clipboard?.writeText(text);setCopied(kind);setTimeout(()=>setCopied(null),1800)}catch{setCopied(null)}}
 const openPlan=()=>{if(!result)return;try{sessionStorage.setItem('operator.openPlan',result.output.id)}catch{/* Browser storage may be unavailable. */}openReports()}
 const another=()=>{setInputs({});setResult(null);setCopied(null);setStep('choose')}
 return <section className="guided-builder"><div className="builder-intro"><div><span className="eyebrow">BUILD SOMETHING</span><h3>{step==='choose'?'What do you want to prepare?':selected.name}</h3><p>{step==='choose'?<>Choose a useful business asset for <b>{project.name}</b>. You’ll get a plan, actions, and milestones—never an automatic launch.</>:selected.description}</p></div><Badge tone="live">Planning only</Badge></div>
  <div className="builder-steps"><span className={step==='choose'?'active':'done'}>1. Choose</span><span className={step==='answer'?'active':step==='review'||step==='result'?'done':''}>2. Tell us</span><span className={step==='review'?'active':step==='result'?'done':''}>3. Review</span></div>
  {step==='choose'&&<div className="builder-card-grid">{builderWorkflows.map(item=><button key={item.id} onClick={()=>choose(item.id)}><span>{item.category==='website'?'◎':item.category==='ads'?'◉':item.category==='app'?'⌁':item.category==='automation'?'↗':'✦'}</span><b>{item.name}</b><small>{item.description}</small></button>)}</div>}
  {step==='answer'&&<div className="builder-question-card"><div className="builder-form-head"><Badge>{selected.bestFor}</Badge><p>Answer what you can. Blank answers get sensible starting points.</p><button onClick={useDefaults}>I don’t know yet — use helpful defaults</button></div><div className="builder-inputs">{selected.inputPrompts.map(item=><label key={item.id}>{item.label}<input value={inputs[item.id]||''} onChange={event=>setInputs(current=>({...current,[item.id]:event.target.value}))} placeholder={item.placeholder}/><small>{item.helper}</small></label>)}</div><div className="builder-flow-actions"><button onClick={()=>setStep('choose')}>Back</button><button className="primary" onClick={()=>setStep('review')}>Review my answers</button></div></div>}
  {step==='review'&&<div className="builder-review"><span className="eyebrow">READY TO REVIEW</span><h3>Here’s what SmallBiz Agent will use</h3><p>Check these starting points. You can go back and edit anything before creating the plan.</p><dl>{selected.inputPrompts.map(item=><div key={item.id}><dt>{item.label}</dt><dd>{usedInputs[item.id]}</dd></div>)}</dl><div className="planning-reminder"><b>Planning only</b><span>Nothing will be published, deployed, sent, or spent. Sensitive future actions always need approval.</span></div>{selected.category==='ads'&&<div className="ad-safety"><b>Campaign plan only</b><span>No ad will be launched and no money will be spent.</span></div>}<div className="builder-flow-actions"><button onClick={()=>setStep('answer')}>Edit my answers</button><button className="primary" onClick={build}>Create my plan</button></div></div>}
  {step==='result'&&result&&<div className="builder-result-polished"><header><span className="result-check">✓</span><div><span className="eyebrow">YOUR PLAN IS READY</span><h3>{result.output.title}</h3><p>{result.output.summary}</p></div></header><div className="builder-created"><section><b>What was created</b><span>1 report saved</span><span>{result.actions.length} suggested actions added</span><span>{result.milestones.length} milestones added</span><span>{result.approvals.length?`${result.approvals.length} simulated approval preview created`:'No approval needed for this plan'}</span></section><section><b>Suggested next actions</b>{result.output.recommendedNextSteps?.slice(0,3).map(item=><span key={item}>✓ {item}</span>)}</section></div><div className="planning-reminder"><b>Planning only · no real action taken</b><span>Nothing was published, deployed, sent, or spent. Approval is required before any sensitive future action.</span></div>{selected.category==='ads'&&<div className="ad-safety"><b>No ad was launched. No money was spent.</b><span>This is a campaign plan only. No ad platform or payment method is connected.</span></div>}<div className="builder-result-actions"><button onClick={()=>copy('summary')}>{copied==='summary'?'Summary copied':'Copy summary'}</button><button onClick={()=>copy('full')}>{copied==='full'?'Plan copied':'Copy full plan'}</button><button onClick={openPlan}>Open plan</button><button onClick={openActions}>Open project actions</button>{result.approvals.length>0&&<button onClick={openApprovals}>Review approval preview</button>}<button className="primary" onClick={another}>Build something else</button></div></div>}
 </section>
}
